### ISSUE TITLE
AttributeError: module 'uamqp' has no attribute 'authentication'

### ISSUE THREAD

**Issue by mpatsalides-hyperio** [Azure/azure-iot-cli-extension#111]
Hi,

When I run the command **az iot hub monitor-events -n {}** while being authenticated I get the following error:

AttributeError: module 'uamqp' has no attribute 'authentication'

Can you help me resolve this issue?

Thanks!

Some more information are found below:

## Describe the bug

**Command Name**
`az iot hub monitor-events
Extension Name: azure-cli-iot-ext. Version: 0.8.4.`

**Errors:**
```
module 'uamqp' has no attribute 'authentication'
Traceback (most recent call last):
pip-install-p8t_6awn\knack\knack\cli.py, ln 206, in invoke
cli\core\commands\__init__.py, ln 603, in execute
cli\core\commands\__init__.py, ln 661, in _run_jobs_serially
cli\core\commands\__init__.py, ln 654, in _run_job
Temp\pip-install-p8t_6awn\six\six.py, ln 693, in reraise
cli\core\commands\__init__.py, ln 631, in _run_job
...
azext_iot\operations\events3\_builders.py, ln 35, in _build_auth_container
    return uamqp.authentication.SASTokenAsync.from_shared_access_key(sas_uri, target['policy'], target['primarykey'])
AttributeError: module 'uamqp' has no attribute 'authentication'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az iot hub monitor-events -n {}`

## Environment Summary
```
Windows-10-10.0.17763-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.75
azure-cli-iot-ext 0.8.4

Extensions:
azure-cli-iot-ext 0.8.4

```

**Comment by mpatsalides-hyperio** [comment]
I have resolved the issue by running the following command:

az iot hub monitor-events -n {} --repair

It was an uamqp version related issue.

**Comment by digimaun** [comment]
@mpatsalides-hyperio , thank you for creating both the issue and resolution for it in case others run into the same thing. As you know, the `--repair` flag is to force a new installation of the uamqp dependency in case of configuration problems like this.

One bit of data that will help future improvements - did you update your IoT extension from a previous install or was it a fresh installation? If it was an update, what was the update path you used?

Thank you.
