### ISSUE TITLE
The extension does not support python 3.8 when monitor messages

### ISSUE THREAD

**Issue by blackchoey** [Azure/azure-iot-cli-extension#128]
When I tries to monitor messages in python 3.8, `Failure updating uamqp` error is raised by the extension.

**Comment by digimaun** [comment]
Thanks for bringing this problem up. We are definitely aware of the issue - currently investigating/working out some issues with the underlying protocol provider (uamqp).

**Comment by digimaun** [comment]
The fix is coming in version 0.8.9 which we are releasing soon.

**Comment by digimaun** [comment]
@blackchoey You could try with our newly [released 0.8.9](https://github.com/Azure/azure-iot-cli-extension/releases/tag/v0.8.9) (via `az extension add --source` method) otherwise we have a PR on the CLI extension index [here](https://github.com/Azure/azure-cli-extensions/pull/1231).

**Comment by digimaun** [comment]
Issue should be resolved.
