### ISSUE TITLE
Convert all query operation results to YAML before display to CLI users.

### ISSUE THREAD

**Issue by WilliamBerryiii** [Azure/azure-iot-cli-extension#13]
I'd like to suggest that the JSON results from CLI calls are converted to YAML for display by default and JSON as optional.  That way the output would be more human readable than sifting through tabs, braces and brackets for every operation result.  It would mean adding a pyyaml dependency, but I feel like the developer experience would be significantly better.

**Comment by digimaun** [comment]
Have you tried the 'table' output format option? i.e.

```az iot hub device-identity list -n [Your hub] -o table```

You can customize the output with '--query', this uses JMESPath style lookups...

Random example:
```az iot hub device-identity list -n [Your hub] -o table --query "[].{name:deviceId, edge:capabilities.iotEdge}"```

You can set your default output option using ```az configure``` so you don't have to keep specifying it (default is json).

What are your thoughts on that?

**Comment by digimaun** [comment]
Good news, CLI core supports yaml  output format by default! Upgrade to a newer Az CLI version and check it out (append -o yaml).

Feel free to open this issue for more discussion.
