### ISSUE TITLE
Allow edge support when creating enrollments and enrollment groups in DPS

### ISSUE THREAD

**Issue by jlorich** [Azure/azure-iot-cli-extension#131]
Right now I can create an edge device in *IoT hub* with `--enable-edge`, however in DPS there is no option to create an enrollment or enrollment group for edge devices.  You must create the enrollment then go manually flip the edge switch in the portal.

It would be great to bring the `--enable-edge` flag to the DPS `enrollment` and `enrollment-group` create commands.

**Comment by digimaun** [comment]
Related issues:

- https://github.com/MicrosoftDocs/azure-docs/issues/47526
- https://github.com/Azure/azure-cli-extensions/issues/468
- https://github.com/Azure/azure-cli-extensions/issues/1248

**Comment by kmansel** [comment]
We have a large client that is requesting this functionality as well.  Looks like it hasn't been triaged yet?

**Comment by digimaun** [comment]
We've [released version](https://github.com/Azure/azure-iot-cli-extension/releases/tag/v0.9.1) `0.9.1` that covers this functionality for individual/group enrollment create/update.

The extension index PR is [in flight](https://github.com/Azure/azure-cli-extensions/pull/1315).

You'll quickly notice a new extension alias - `azure-iot`. This is the new extension alias moving forward. You'll be able to `az extension add --name azure-iot` after the extension index PR is merged.

Until then you can install via source method. Also, pinning to a specific version of the IoT extension for production (via the source method) is a good idea.

Here is an example:

`az extension add --source 'https://github.com/Azure/azure-iot-cli-extension/releases/download/v0.9.1/azure_iot-0.9.1-py2.py3-none-any.whl'`

**Comment by digimaun** [comment]
The `azure-iot` extension is now available on the index and can be installed via the syntax mentioned earlier.

**Comment by kmansel** [comment]
Thank you very much for the quick resolution.  Super appreciated.
