### ISSUE TITLE
az iot edge get-modules?

### ISSUE THREAD

**Issue by thnk2wn** [Azure/azure-iot-cli-extension#145]
There's a command [az iot edge set-modules](https://docs.microsoft.com/en-us/cli/azure/ext/azure-cli-iot-ext/iot/edge?view=azure-cli-latest#ext-azure-cli-iot-ext-az-iot-edge-set-modules) but best I can tell there's no way to get what modules versions are currently installed?

There's [az iot hub module-identity list](https://docs.microsoft.com/en-us/cli/azure/ext/azure-cli-iot-ext/iot/hub/module-identity?view=azure-cli-latest#ext-azure-cli-iot-ext-az-iot-hub-module-identity-list) and corresponding `show` but that doesn't provide module version information.

Modules aren't in the twin so the `module-twin` commands aren't of use.

Regardless if modules were deployed via `set-modules` or via an at-scale deployment, it'd be nice to see what versions are currently installed from the CLI.  

Likewise it'd be nice to monitor the progress of a `set-modules` operation. I thought 
[az iot hub monitor events](https://docs.microsoft.com/en-us/cli/azure/ext/azure-cli-iot-ext/iot/hub?view=azure-cli-latest#ext-azure-cli-iot-ext-az-iot-hub-monitor-events) might be of use here but it didn't display anything.

For at scale deployments, I think `az iot edge deployment` commands will work here but it'd be helpful to get module info outside of at-scale deployments.

At present it seems I'm forced to go to the portal or ssh into the device to see either current module info or `set-module` progress.

Does this functionality exist in some form? If not, is it something that can be considered for adding?

**Comment by digimaun** [comment]
Hey @thnk2wn , thanks for submitting this issue.

The way to achieve what you are trying to do is via the edge runtime system modules - particularly the `$edgeAgent`. `$edgeAgent` is responsible for instantiating and maintaining user module state and reporting status to IoT Hub.

So all you need to do is query the module twin of `$edgeAgent`.

I'll provide an example. In this case I am arbitrarily using powershell (so using single quotes to ignore the $). Also in this scenario in my prior `set-modules` call I have set a simulated temperature sensor module.

I can do this to show all twin properties of `$edgeAgent`:
`az iot hub module-twin show -n myiothub -d myedgedevice -m '$edgeAgent' `


Or, same idea as above but use `--query` to filter on the reported state of user modules:

```
$ az iot hub module-twin show -n myiothub -d myedgedevice -m '$edgeAgent' --query 'properties.reported.modules'

{
  "SimulatedTemperatureSensor": {
    "env": {},
    "exitCode": 0,
    "lastExitTimeUtc": "0001-01-01T00:00:00Z",
    "lastRestartTimeUtc": "0001-01-01T00:00:00Z",
    "lastStartTimeUtc": "2020-03-11T19:21:19.7388894Z",
    "restartCount": 0,
    "restartPolicy": "always",
    "runtimeStatus": "running",
    "settings": {
      "createOptions": "{}",
      "image": "mcr.microsoft.com/azureiotedge-simulated-temperature-sensor:1.0",
      "imageHash": "sha256:11307206e446345e4557849f253129c38dee009fdca423c8470f96df84ee914d"
    },
    "status": "running",
    "statusDescription": "running",
    "type": "docker",
    "version": "1.0"
  }
}
```

**Comment by thnk2wn** [comment]
Thanks. It wasn't obvious / intuitive to me to query the module twin of the Edge Agent.

I'll experiment on filtering, parsing, formatting that data. 

To get a friendlier table output with say just version and status of user modules, what would the syntax be? I tried the below and various variations but get no output:

````shell
az iot hub module-twin show -n myiothub -d myEdgeDevice -m '$edgeAgent' --query "properties.reported.modules[].[version,status]" -o table
````

Could both desired and reported versions be retrieved and displayed in this manner in a single call?

Ultimately I think this'll work but may be more verbose and cumbersome than some dedicated az iot edge command that would display version info more similar to say what the Portal shows for edge device modules or what you get when running `sudo iot edge list` on the device.

**Comment by digimaun** [comment]
Appreciate the feedback. I am not opposed to a new `az iot edge` command that simplifies retrieval of the desired vs reported state of modules for an edge device. 

However, here are a couple `--query` variations that could help. One issue is the default returned edgeAgent data structure is not normalized optimally for jmespath queries because the collection of modules are stored as a hash (module names are keys) instead of an array.

###Examples###


Iterate through every reported module showing the image, version and status - output in table format

`--query 'properties.reported.modules.* | [*].{Image:settings.image, Version:version, Status:status}' -o table`

Same as above but for a specific module

`
--query 'properties.reported.modules.SimulatedTemperatureSensor | {Image:settings.image, Version:version, Status:status}' -o table
`

This one is for a specific module but also includes desired state

`
--query '{reported:properties.reported.modules.SimulatedTemperatureSensor, desired:properties.desired.modules.SimulatedTemperatureSensor} | {DesiredImageUri:@.desired.settings.image, DesiredStatus:@.desired.status, DesiredVersion:@.desired.version, ReportedImageUri:@.reported.settings.image, ReportedStatus:@.reported.status, ReportedVersion:@.reported.version}' -o table`

**Comment by thnk2wn** [comment]
Ahh, that's why. Twin docs not supporting arrays strikes again.

Thanks, that works. Below is a script wrapping some of this if of use to others.

````powershell
# Get script help with: Get-Help -Detailed ./device-modules.ps1

<#
    .SYNOPSIS
        Lists desired and/or reported state of modules on an Edge device in a friendly table format.

    .DESCRIPTION
        Displays versions, status and related module state from desired and/or reported properties.
        This information is a bit harder to extract from the Azure CLI in a friendly format.

    .PARAMETER deviceId
        Device id to get module state from.

    .PARAMETER hubName
        Optional IoT hub name, defaulting to 'default-iot-hub'.

    .PARAMETER state
        Optional state to report - "desired", "reported", or "all". Defaults to "all".

    .INPUTS
        Script does not accept pipeline input.

    .OUTPUTS
        Formatted output of 'az iot hub module-twin show' for Edge Agent.

    .EXAMPLE
        pwsh>./device-modules.ps1 -device "24-04-F3-CB-C7-61" -hub hub-name

        Lists desired and reported module versions in table format.

    .EXAMPLE
        pwsh>./device-modules.ps1 -device "24-04-F3-CB-C7-61" -hub hub-name -state reported

        Lists only reported module versions in table format.

    .LINK
        https://github.com/Azure/azure-iot-cli-extension/issues/145

    .NOTES
        https://github.com/Azure/azure-iot-cli-extension/issues/145
    #>
[CmdletBinding()]
param(
    [Parameter(Mandatory=$true)]
    [string]
    $deviceId,

    [String]
    $hubName = "default-iot-hub",

    [ValidateSet("desired", "reported", "all")]
    [String]
    $state = "all"
)

$states = @()

if ($state -in "desired", "all") {
    $states += "desired"
}

if ($state -in "reported", "all") {
    $states += "reported"
}

foreach ($state in $states) {
    $stateTitle = (Get-Culture).TextInfo.ToTitleCase($state)

    # Last Start Time only applicable to Reported props; won't show up for Desired

    az iot hub module-twin show `
        -n $hubName `
        -d "$deviceId" `
        -m '$edgeAgent' `
        --query "properties.$state.modules.* | [*].{$($stateTitle)Image:settings.image, Version:version, Status:status, LastStartUtc:lastStartTimeUtc}" `
        -o table

    ""
}
````
