### ISSUE TITLE
GetLogs command not working

### ISSUE THREAD

**Issue by mahdighorbanpour** [Azure/azure-iot-cli-extension#154]
I have installed the latest version of azure iot runtime 1.0.9 and added the entries for enabling experimental mode both for user variables and also system variables. Edge device operating system is windows 10 1809. The GetLogs direct command is not working.

**Command Name**
`az iot hub invoke-module-method
Extension Name: azure-iot. Version: 0.9.1.`

**Errors:**
```
[Errno 2] No such file or directory: '\\'
Traceback (most recent call last):
pip-install-_1mlo87m\knack\knack\cli.py, ln 215, in invoke
cli\core\commands\__init__.py, ln 625, in execute
cli\core\commands\__init__.py, ln 689, in _run_jobs_serially
cli\core\commands\__init__.py, ln 682, in _run_job
Temp\pip-install-_1mlo87m\six\six.py, ln 703, in reraise
cli\core\commands\__init__.py, ln 659, in _run_job
cli\core\commands\__init__.py, ln 324, in __call__
azure\cli\core\__init__.py, ln 531, in default_command_handler
...
azure-iot\azext_iot\common\utility.py, ln 158, in read_file_content
    with codecs_open(file_path, encoding=encoding) as f:
Azure\CLI2\lib\codecs.py, ln 897, in open
    file = builtins.open(filename, mode, buffering)
FileNotFoundError: [Errno 2] No such file or directory: '\\'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az iot hub invoke-module-method -n {} -d {} -m {} --mn {} --mp {}`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Installer: MSI

azure-cli 2.3.1

Extensions:
azure-iot 0.9.1

```

**Comment by digimaun** [comment]
@mahdighorbanpour thanks for submitting the issue.

Based on your logs the `invoke-module-method` is not actually invoking any methods yet. It's unable to process the input argument for `--mp`.

Can you share a generic version of what you are passing to `--mp`?

Looking at the [docs here](https://github.com/Azure/iotedge/blob/master/doc/built-in-logs-pull.md#getlogs) there is an expected payload format, which is similar to the UploadLogs except it doesn't have the "sasUrl" property.

The "--method-payload / --mp" argument supports either raw json (however shell rules apply) input from file path.

**Comment by digimaun** [comment]
Closing issue as we've been unable to receive more details to repro. If you are still having problems, please comment and we can re-open.
