### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ericwol-msft** [Azure/azure-iot-cli-extension#156]
**Describe the bug**
"az iot hub device-twin update" sends the whole twin json in the PATCH request, no just the changed property.

**To Reproduce**
Create an IoT hub and a device

Send a device twin update to the device 
az iot hub device-twin update -d <devicename> -n <iothubname> --set properties.desired.changeOilReminder=\"Today\"

Send a different property
`az iot hub device-twin update -d <devicename> -n <iothubname> --set properties.desired.settings=\{\"desired_maxSpeed\":12\}`

Note: The whole twin desired properties are send, not just the one that is changed

**Expected behavior**
When doing a device twin update, only the new desired property should be sent to the hub.

**Environment (please complete the following information):**
Windows 10
cmd
{
  "azure-cli": "2.3.1",
  "azure-cli-command-modules-nspkg": "2.0.3",
  "azure-cli-core": "2.3.1",
  "azure-cli-nspkg": "3.0.4",
  "azure-cli-telemetry": "1.0.4",
  "extensions": {
    "azure-iot": "0.9.1"
  }
}

**Comment by digimaun** [comment]
This issue should be resolved in `0.9.2` via new patch arguments `--desired` and `--tags`. Until the extension is available on the extension index (usually takes a few days), you will have to pin the package installation via `--source`.

The steps are as follows:
- First remove the existing installation: `az extension remove --name azure-iot`
- Then add the latest via source: `az extension add --source "https://github.com/Azure/azure-iot-cli-extension/releases/download/v0.9.2/azure_iot-0.9.2-py2.py3-none-any.whl"`
