### ISSUE TITLE
Error running az iot hub device-identity create

### ISSUE THREAD

**Issue by dbafromthecold** [Azure/azure-iot-cli-extension#165]
## Describe the bug

Error generated when creating a device via the cli in azure-cli.
I installed the module via pip install azure-mgmt-iothub but am still getting the error.

**Command Name**
`az iot hub device-identity create
Extension Name: azure-iot. Version: 0.9.1.`

**Errors:**
```
No module named 'azure.mgmt.iothub.iot_hub_client'
Traceback (most recent call last):
pip-install-_1mlo87m\knack\knack\cli.py, ln 215, in invoke
cli\core\commands\__init__.py, ln 625, in execute
cli\core\commands\__init__.py, ln 689, in _run_jobs_serially
cli\core\commands\__init__.py, ln 682, in _run_job
Temp\pip-install-_1mlo87m\six\six.py, ln 703, in reraise
cli\core\commands\__init__.py, ln 659, in _run_job
cli\core\commands\__init__.py, ln 324, in __call__
...
    client = iot_hub_service_factory(cmd.cli_ctx)
cliextensions\azure-cli-iot-ext\azext_iot\_factory.py, ln 29, in iot_hub_service_factory
    from azure.mgmt.iothub.iot_hub_client import IotHubClient
ModuleNotFoundError: No module named 'azure.mgmt.iothub.iot_hub_client'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az iot hub device-identity create --device-id {} --hub-name {}`

## Expected Behavior
Device is created in Azure

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Installer: MSI

azure-cli 2.3.1
azure-cli-iot-ext 0.7.1

Extensions:
azure-cli-iot-ext 0.7.1
azure-iot 0.9.1

```

**Comment by digimaun** [comment]
Hi @dbafromthecold thanks for submitting this issue.

Please first remove the legacy IoT extension `azure-cli-iot-ext` using the command `az extension remove --name azure-cli-iot-ext`.  Both `azure-iot` (the modern extension alias) and `azure-cli-iot-ext` should not co-exist. You may have to re-install `azure-iot` as well.

After that, your issue should be resolved.

**Comment by dbafromthecold** [comment]
Worked a treat, thank you!
