### ISSUE TITLE
[iotedge] new function request - export deploytment.json from an existing iot edge device

### ISSUE THREAD

**Issue by yphuangms** [Azure/azure-iot-cli-extension#17]
As we know that there exists "az iot hub **apply-configuration**" command to apply deployment configuration to an edge device, may we have an "**az iot hub export-configuration**" that could output the existing deployment to json file? 

This will help to save a lot of time for developer/operator to keep their deployment settings, and to reuse the settings.

Thanks!

**Comment by digimaun** [comment]
This has been a long time coming, but we have a new preview command `az iot edge export-modules` in the latest release (currently `0.19.1`) which should cover this ask.

We encourage you to give it a try and let us know of any feedback.
