### ISSUE TITLE
az iot central app monitor-events raise an error in Azure Shell

### ISSUE THREAD

**Issue by pietrobr** [Azure/azure-iot-cli-extension#175]
## Describe the bug

**Command Name**
`az iot central app monitor-events
Extension Name: azure-cli-iot-ext. Version: 0.8.0.`

**Errors:**
```
400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 631, in execute
    raise ex
cli/core/commands/__init__.py, ln 695, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
...
python3.6/site-packages/requests/models.py, ln 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az iot central app monitor-events --app-id {} --properties {}`

## Environment Summary
```
Linux-4.15.0-1077-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Installer: DEB

azure-cli 2.4.0 *
azure-cli-iot-ext 0.8.0

Extensions:
azure-iot 0.9.1
azure-cli-iot-ext 0.8.0
aks-preview 0.4.5

```

**Comment by digimaun** [comment]
Hi @pietrobr , thanks for submitting this issue. Can you please try re-running `az login` in cloudshell and then running the monitor command again?

Also, you only want one IoT extension installed `azure-iot`. The `azure-cli-iot-ext` is the legacy IoT extension Id and should be removed.

**Comment by pietrobr** [comment]
Hi @digimaun running az login in the cloud shell the app monitor event starts as expected. I've aslo removed the legacy azure-cli-iot-ext. Thanks for the help and let me know about the legacy extension!
