### ISSUE TITLE
IoT Hub module not available in Cloud Shell

### ISSUE THREAD

**Issue by mredd** [Azure/azure-iot-cli-extension#181]
## Describe the bug

**Command Name**
`az iot hub monitor-events`
Extension Name: azure-iot. Version: 0.9.2.

**Errors:**
```
No module named 'azure.mgmt.iothub.iot_hub_client'
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 631, in execute
    raise ex
cli/core/commands/__init__.py, ln 695, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 688, in _run_job
    six.reraise(*sys.exc_info())
...
azure-cli-iot-ext/azext_iot/common/_azure.py, ln 95, in get_iot_hub_connection_string
    client = iot_hub_service_factory(cmd.cli_ctx)
cliextensions/azure-cli-iot-ext/azext_iot/_factory.py, ln 29, in iot_hub_service_factory
    from azure.mgmt.iothub.iot_hub_client import IotHubClient
ModuleNotFoundError: No module named 'azure.mgmt.iothub.iot_hub_client'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az extension add --name azure-iot`
- `az iot hub monitor-events --hub-name {} --output {}`

## Expected Behavior

Azure Cloud Shell can be used for monitoring events on the IoT Hub.

## Environment Summary
```
Linux-4.15.0-1082-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Installer: DEB

azure-cli 2.4.0 *
azure-cli-iot-ext 0.8.0

Extensions:
azure-cli-iot-ext 0.8.0
azure-iot 0.9.2

```

**Comment by digimaun** [comment]
Hi @mredd , please try the resolution mentioned [in the following issue](https://github.com/Azure/azure-iot-cli-extension/issues/165#issuecomment-614878544). After that the problem should be resolved.

**Comment by mredd** [comment]
The described solution works. @digimaun Thank you for the quick response!
