### ISSUE TITLE
[bug] DPS Enrollment Update Gives Unclear Error

### ISSUE THREAD

**Issue by SpaceKatt** [Azure/azure-iot-cli-extension#182]
**Describe the bug**

`az iot dps enrollment update` results in failure, and the failure message is unclear (`Expecting value: line 1 column 1 (char 0)`).

**To Reproduce**

1. Create enrollment in DPS via TPM attestation.
2. Try to update the initital device twin properties...

```
$ az iot dps enrollment update -g "resourceGroup" --dps-name "dpsName" --enrollment-id "ENROLLMENT_ID" --props 'properties.desired.timeZone="FOOBAR"'
Expecting value: line 1 column 1 (char 0)
```

**Expected behavior**

I expect the device twin's initial properties to be updated.

```
$ az iot dps enrollment update -g "resourceGroup" --dps-name "dpsName" --enrollment-id "ENROLLMENT_ID" --props 'properties.desired.timeZone="FOOBAR"'
SUCCESS: Property `properties.desired.timeZone` was set to `FOOBAR`
```

**Screenshots**

**Environment (please complete the following information):**

- OS: MacOS X
- Shell: bash
- Az CLI version: 2.3.1
- IoT extension version: 0.9.2
- Python version (if pip installed): 3.7.5

**Additional context**

**Comment by digimaun** [comment]
Hey @SpaceKatt , thanks for submitting this issue. Yea, I agree the message can be made more clear, we'll set a work item to improve in future releases.

This update command is actually not in the "generic CLI update command" style. So you are unable to use 'PATCH' syntax for `--props`. Instead you'll need to provide a raw json snippet (shell rules apply).

Here is an example:
`--props '{"properties":{"desired":{"timeZone": "FOOBAR"}}}'`

That should resolve this issue. Let me know.

**Comment by SpaceKatt** [comment]
That did solve my issue, thank you~

**Comment by digimaun** [comment]
Excellent, thanks for reporting back on it.
