### ISSUE TITLE
Following IoT-Edge trackt fails

### ISSUE THREAD

**Issue by ArendSmit** [Azure/azure-iot-cli-extension#186]
### **This is autogenerated. Please review and update as needed.**
https://docs.microsoft.com/nl-nl/learn/modules/deploy-prebuilt-module-edge-device/4-exercise-setup-communication (in dutch)

In the step making a device-identity the python fails with an  incomprehensible stacktrace.

apparently this is due to a failure in the first step az extension add --name azure-cli-iot-ext it fails because it is already installed with an incompatible version.

See: https://github.com/Azure/azure-cli/issues/13093

Please add this fix to the tutorial.

execute
az extension remove --name azure-cli-iot-ext
 before 
az extension add --name azure-cli-iot-ext

## Describe the bug

**Command Name**
`az iot hub device-identity create
Extension Name: azure-cli-iot-ext. Version: 0.7.1.`

**Errors:**
```
No module named 'azure.mgmt.iothub.iot_hub_client'
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 631, in execute
    raise ex
cli/core/commands/__init__.py, ln 695, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
...
azure-cli-iot-ext/azext_iot/common/_azure.py, ln 90, in get_iot_hub_connection_string
    client = iot_hub_service_factory(cmd.cli_ctx)
cliextensions/azure-cli-iot-ext/azext_iot/_factory.py, ln 29, in iot_hub_service_factory
    from azure.mgmt.iothub.iot_hub_client import IotHubClient
ModuleNotFoundError: No module named 'azure.mgmt.iothub.iot_hub_client'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az iot hub device-identity create --hub-name {} --device-id {} --edge-enabled`

## Environment Summary
```
Linux-4.15.0-1082-azure-x86_64-with-debian-stretch-sid
Python 3.6.5
Installer: DEB

azure-cli 2.4.0 *
azure-cli-iot-ext 0.7.1

Extensions:
azure-cli-iot-ext 0.7.1

```

**Comment by digimaun** [comment]
Hi @ArendSmit , thanks for submitting this issue.

Please follow the instructions in the [News section](https://github.com/Azure/azure-iot-cli-extension/blob/dev/README.md#news) on the readme, or look at an [identical issue](https://github.com/Azure/azure-iot-cli-extension/issues/165#issuecomment-614878544) which will have the same resolution path.

After that your issue should be resolved.

**Comment by digimaun** [comment]
We'll also look into fixing the tutorial instructions.

**Comment by digimaun** [comment]
The tutorial should now be updated/fixed. Thanks again for submitting the issue.
