### ISSUE TITLE
az iot hub monitor-events

### ISSUE THREAD

**Issue by hustbill** [Azure/azure-iot-cli-extension#188]
## Describe the bug

**Command Name**
`az iot hub monitor-events
Extension Name: azure-cli-iot-ext. Version: 0.8.9.`

**Errors:**
```
ErrorCodes.UnknownError: Connection in an unexpected error state.
Traceback (most recent call last):
pip-install-z6h9b3s8\knack\knack\cli.py, ln 215, in invoke
cli\core\commands\__init__.py, ln 631, in execute
cli\core\commands\__init__.py, ln 695, in _run_jobs_serially
cli\core\commands\__init__.py, ln 688, in _run_job
Temp\pip-install-z6h9b3s8\six\six.py, ln 703, in reraise
cli\core\commands\__init__.py, ln 665, in _run_job
cli\core\commands\__init__.py, ln 324, in __call__
azure\cli\core\__init__.py, ln 574, in default_command_handler
...
azure-cli-iot-ext\uamqp\async_ops\client_async.py, ln 363, in client_ready_async
    await self._connection.work_async()
azure-cli-iot-ext\uamqp\async_ops\connection_async.py, ln 127, in work_async
    raise self._error
uamqp.errors.ConnectionClose: ErrorCodes.UnknownError: Connection in an unexpected error state.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az iot hub monitor-events -n {} -d {} -t {} --login {} --debug`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Installer: MSI

azure-cli 2.4.0 *
azure-cli-iot-ext 0.8.9

Extensions:
azure-cli-iot-ext 0.8.9

```

**Comment by digimaun** [comment]
Hi @hustbill, first can you try removing the deprecated `azure-cli-iot-ext` and installing `azure-iot` (`azure-iot` is a superset of `azure-cli-iot-ext`) then try running the command again?

If you run into the same error, can you please validate the IoT Hub connection string you pass into `--login`  has the proper permissions?

**Comment by digimaun** [comment]
Closing for now. Please comment and we can re-open.
