### ISSUE TITLE
[Question] How do you develop this extension

### ISSUE THREAD

**Issue by haroldrandom** [Azure/azure-iot-cli-extension#217]
Hi, guys, I am from Azure/azure-cli.

We are considering onboarding a feature on azdev which is used to develop Azure CLI and Azure CLI extension, and that feature might break some existing UX.

I would like to know how do you develop this extension and make sure whether we could onboard that feature.

Could you give a brief introduction like how to run linter, how to run test, how to orginaze with Azure/azure-cli code, folder structure? Did you use azdev?

**Comment by digimaun** [comment]
Hey @haroldrandom - yea we know you :)

There is an overview of our dev setup process [here](https://github.com/Azure/azure-iot-cli-extension/blob/dev/CONTRIBUTING.md). Also explains how to run tests (we are fans of `pytest`).

Specifically regarding azdev, we generally use azdev for setting up the base AzureCLI in the virtualenv via `azdev setup -c ...` and also for the cli lint feature. For example used in our [CI pipeline](https://github.com/Azure/azure-iot-cli-extension/blob/dev/.azure-devops/merge.yml#L136) but its used in the inner dev loop as well, hence the issue we created in the [azdev repo](https://github.com/Azure/azure-cli-dev-tools/issues/199) to allow azdev to be easier to use in the dev loop.

As far as other linting goes, we make use of `flake8` and `pylint` with our own rule set. You can see our other dev tool packages in [dev_requirements](https://github.com/Azure/azure-iot-cli-extension/blob/dev/dev_requirements).

**Comment by haroldrandom** [comment]
As for the `use azdev for setting up the base AzureCLI in the virtualenv`, do you use with `-r` parameter? and how many extension repos do you specify?

**Comment by haroldrandom** [comment]
Also, we are ahout to remove the inner azdev of Azure/azure-cli, that's the tools/ folder `git+https://github.com/Azure/azure-cli@dev#egg=azure-cli-dev-tools`

**Comment by digimaun** [comment]
Thanks for the notification about this change.

```quote
Also, we are ahout to remove the inner azdev of Azure/azure-cli, that's the tools/ folder git+https://github.com/Azure/azure-cli@dev#egg=azure-cli-dev-tools
```

As for further azdev questions, will talk to you about them offline.
