### ISSUE TITLE
Creates invalid device SAS token

### ISSUE THREAD

**Issue by dominicbetts** [Azure/azure-iot-cli-extension#22]
I run the following command to create a device SAS token:

```
az iot hub generate-sas-token --policy-name device --device-id MyTestDevice --hub-name MyHubName
```

If I try to use the generated token in the following Node.js code, I get a **Connection refused: Not authorised** error:

```
var Protocol = require('azure-iot-device-mqtt').Mqtt;
var Client = require('azure-iot-device').Client;
var test_token = 'generated token here';
var client = Client.fromSharedAccessSignature(test_token, Protocol);
...
client.open(connectCallback);
```

**Comment by digimaun** [comment]
@dominicbetts  This should be fixed in v0.4.3 - please update and try again. I am closing this issue for now, but if it still doesn't work please reopen.
