### ISSUE TITLE
az IoT Hub issue

### ISSUE THREAD

**Issue by vnanda20** [Azure/azure-iot-cli-extension#228]
## Describe the bug

**Command Name**
`az iot hub device-identity create
Extension Name: azure-iot. Version: 0.9.7.`

**Errors:**
```
400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 215, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 654, in execute
    raise ex
cli/core/commands/__init__.py, ln 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
...
python3.6/site-packages/msrestazure/azure_active_directory.py, ln 486, in get_msi_token
    result.raise_for_status()
python3.6/site-packages/requests/models.py, ln 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az iot hub device-identity create --hub-name {} --device-id {}`

## Environment Summary
```
Linux-4.15.0-1092-azure-x86_64-with-debian-stretch-sid (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.9.1 *

Extensions:
azure-iot 0.9.7

```

**Comment by prbans** [comment]
Have you tried doing an `az login`?

**Comment by digimaun** [comment]
There is currently an open issue in cloudshell that manifests this error. The solution is to [re]run `az login` and then execute the original command.

Linking to the running issue thread https://github.com/Azure/azure-cli/issues/11749

**Comment by digimaun** [comment]
Please comment if the suggested workaround does not work for you.
