### ISSUE TITLE
ERROR: No matching extensions for 'azure-cli-iot-ext'[bug] <concise bug label here>

### ISSUE THREAD

**Issue by livneros** [Azure/azure-iot-cli-extension#229]
when I try to install the azure-cli-iot-ext on on Azure CLI task on Azure Pipeline, I get an error claiming no matching extension exists...

azure cli version - azure-cli (2.0.54)

when I try to run

az extension add --name azure-cli-iot-ext

I get this error...
No matching extensions for 'azure-cli-iot-ext'. Use --debug for more information.

if I run it with --debug, I get..
DEBUG: Command arguments: ['extension', 'add', '--name', 'azure-cli-iot-ext', '--debug']
DEBUG: Event: Cli.PreExecute []
DEBUG: Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7f851f033c80>, <function OutputProducer.on_global_arguments at 0x7f851f06d2f0>, <function CLIQuery.on_global_arguments at 0x7f851f021d90>]
DEBUG: Event: CommandInvoker.OnPreCommandTableCreate []
DEBUG: Installed command modules ['acr', 'acs', 'advisor', 'ams', 'appservice', 'backup', 'batch', 'batchai', 'billing', 'botservice', 'cdn', 'cloud', 'cognitiveservices', 'configure', 'consumption', 'container', 'cosmosdb', 'dla', 'dls', 'dms', 'eventgrid', 'eventhubs', 'extension', 'feedback', 'find', 'hdinsight', 'interactive', 'iot', 'iotcentral', 'keyvault', 'lab', 'maps', 'monitor', 'network', 'policyinsights', 'profile', 'rdbms', 'redis', 'relay', 'reservations', 'resource', 'role', 'search', 'servicebus', 'servicefabric', 'signalr', 'sql', 'storage', 'vm']
DEBUG: Loaded module 'acr' in 0.015 seconds.
DEBUG: Loaded module 'acs' in 0.003 seconds.
DEBUG: Loaded module 'advisor' in 0.001 seconds.
DEBUG: Event: CommandLoader.OnLoadCommandTable []
DEBUG: Loaded module 'ams' in 0.005 seconds.
DEBUG: Loaded module 'appservice' in 0.006 seconds.
DEBUG: Loaded module 'backup' in 0.003 seconds.
DEBUG: Event: CommandLoader.OnLoadCommandTable []
DEBUG: Loaded module 'batch' in 0.009 seconds.
DEBUG: Loaded module 'batchai' in 0.003 seconds.
DEBUG: Loaded module 'billing' in 0.002 seconds.
DEBUG: Loaded module 'botservice' in 0.003 seconds.
DEBUG: Event: CommandLoader.OnLoadCommandTable []
DEBUG: Loaded module 'cdn' in 0.002 seconds.
DEBUG: Loaded module 'cloud' in 0.001 seconds.
DEBUG: Loaded module 'cognitiveservices' in 0.001 seconds.
DEBUG: Loaded module 'configure' in 0.001 seconds.
DEBUG: Loaded module 'consumption' in 0.002 seconds.
DEBUG: Loaded module 'container' in 0.002 seconds.
DEBUG: Loaded module 'cosmosdb' in 0.003 seconds.
DEBUG: Loaded module 'dla' in 0.004 seconds.
DEBUG: Loaded module 'dls' in 0.004 seconds.
DEBUG: Loaded module 'dms' in 0.002 seconds.
DEBUG: Loaded module 'eventgrid' in 0.003 seconds.
DEBUG: Loaded module 'eventhubs' in 0.004 seconds.
DEBUG: Loaded module 'extension' in 0.002 seconds.
DEBUG: Loaded module 'feedback' in 0.001 seconds.
DEBUG: Loaded module 'find' in 0.001 seconds.
DEBUG: Loaded module 'hdinsight' in 0.001 seconds.
DEBUG: Loaded module 'interactive' in 0.000 seconds.
DEBUG: Loaded module 'iot' in 0.005 seconds.
DEBUG: Loaded module 'iotcentral' in 0.001 seconds.
DEBUG: Loaded module 'keyvault' in 0.008 seconds.
DEBUG: Loaded module 'lab' in 0.003 seconds.
DEBUG: Loaded module 'maps' in 0.001 seconds.
DEBUG: Loaded module 'monitor' in 0.007 seconds.
DEBUG: Loaded module 'network' in 0.030 seconds.
DEBUG: Loaded module 'policyinsights' in 0.002 seconds.
DEBUG: Loaded module 'profile' in 0.001 seconds.
DEBUG: Loaded module 'rdbms' in 0.006 seconds.
DEBUG: Loaded module 'redis' in 0.002 seconds.
DEBUG: Loaded module 'relay' in 0.003 seconds.
DEBUG: Loaded module 'reservations' in 0.002 seconds.
DEBUG: Loaded module 'resource' in 0.008 seconds.
DEBUG: Loaded module 'role' in 0.004 seconds.
DEBUG: Loaded module 'search' in 0.001 seconds.
DEBUG: Loaded module 'servicebus' in 0.004 seconds.
DEBUG: Loaded module 'servicefabric' in 0.002 seconds.
DEBUG: Loaded module 'signalr' in 0.001 seconds.
DEBUG: Loaded module 'sql' in 0.006 seconds.
DEBUG: Event: CommandLoader.OnLoadCommandTable []
DEBUG: Loaded module 'storage' in 0.034 seconds.
DEBUG: Loaded module 'vm' in 0.014 seconds.
DEBUG: Loaded all modules in 0.231 seconds. (note: there's always an overhead with the first module loaded)
DEBUG: Extensions directory: '/vsts/agent/_work/_temp/.azclitask/cliextensions'
DEBUG: Event: CommandInvoker.OnPreCommandTableTruncate []
DEBUG: Event: CommandInvoker.OnPostCommandTableCreate [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7f851ed2a0d0>, <function register_ids_argument.<locals>.add_ids_arguments at 0x7f851ed55a60>]
DEBUG: Event: CommandInvoker.OnCommandTableLoaded []
DEBUG: Event: CommandInvoker.OnPreParseArgs [<function _documentdb_deprecate at 0x7f851be9cbf8>]
DEBUG: Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7f851f06d378>, <function CLIQuery.handle_query_parameter at 0x7f851f021e18>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x7f851ed55ae8>, <function handler at 0x7f851bdf92f0>]
DEBUG: Extensions directory: '/vsts/agent/_work/_temp/.azclitask/cliextensions'
DEBUG: urllib3.connectionpool : Starting new HTTPS connection (1): aka.ms:443
DEBUG: urllib3.connectionpool : https://aka.ms:443 "GET /azure-cli-extension-index-v1 HTTP/1.1" 301 0
DEBUG: urllib3.connectionpool : Starting new HTTPS connection (1): azurecliextensionsync.blob.core.windows.net:443
DEBUG: urllib3.connectionpool : https://azurecliextensionsync.blob.core.windows.net:443 "GET /index1/index.json HTTP/1.1" 200 459025
DEBUG: Candidates ['azure_cli_iot_ext-0.8.10-py2.py3-none-any.whl', 'azure_cli_iot_ext-0.8.9-py2.py3-none-any.whl']
DEBUG: Candidates ['azure_cli_iot_ext-0.8.10-py2.py3-none-any.whl', 'azure_cli_iot_ext-0.8.9-py2.py3-none-any.whl']
DEBUG: Skipping 'azure_cli_iot_ext-0.8.10-py2.py3-none-any.whl' as not compatible with this version of the CLI. Extension compatibility result: is_compatible=False cli_core_version=2.0.54 min_required=2.0.70 max_required=None
DEBUG: Skipping 'azure_cli_iot_ext-0.8.9-py2.py3-none-any.whl' as not compatible with this version of the CLI. Extension compatibility result: is_compatible=False cli_core_version=2.0.54 min_required=2.0.70 max_required=None
DEBUG: Candidates []
DEBUG: No suitable extensions found.
ERROR: No matching extensions for 'azure-cli-iot-ext'. Use --debug for more information.
INFO: telemetry.save : Save telemetry record of length 2431 in cache
WARNING: telemetry.check : Negative: The /vsts/agent/_work/_temp/.azclitask/telemetry.txt was modified at 2020-08-09 08:30:54.464474, which in less than 600.000000 s

**Comment by prbans** [comment]
I believe az extension add --name azure-cli-iot-ext is deprecated, have you tried 

`az extension add --name azure-iot`

Source: 
https://github.com/Azure/azure-iot-cli-extension#news

**Comment by digimaun** [comment]
We recently removed an old version of `azure-cli-iot-ext` that needed a min core cli of 2.0.24.  There still remains (temporarily) a version of `azure-cli-iot-ext`, but that needs CLI core 2.0.70+.  FWIW Azure CLI 2.0.54 was released December 20, 2018 ...so its highly recommended you upgrade that.

Like prbans mentioned `azure-cli-iot-ext` is deprecated -- `azure-iot` is what replaces it.
