### ISSUE TITLE
Errors running unit tests after developer setup on Windows

### ISSUE THREAD

**Issue by andrew-buckley** [Azure/azure-iot-cli-extension#25]
I'm getting the following test output after following the developer setup instructions. Most of them seem to be related to not finding the paho module.
[output.txt](https://github.com/Azure/azure-iot-cli-extension/files/1920903/output.txt)

**Comment by digimaun** [comment]
Ensure that your pythonpath includes the path to the local extension deployment directory used in the pip install -U --target.

**Comment by digimaun** [comment]
Resolved offline.
