### ISSUE TITLE
Error trying to add route

### ISSUE THREAD

**Issue by francischeung** [Azure/azure-iot-cli-extension#27]
I'm trying to add a route to my IoT Hub.

az iot hub update --name myiothubname --add properties.routing.routes '{"condition":"true","endpointNames":["events"],"isEnabled":true,"name":"defaulteventrount","source":"DeviceMessages"}'

The json I'm sending in the --add command was extracted from when I added the route via the portal.
I'm just creating an explicit route to the "events" endpoint. Later I want to add a route to a custom endpoint.

This is the error I'm getting:
**Unable to build a model: Cannot deserialize as [str] an object of type <class 'str'>, DeserializationError: Cannot deserialize as [str] an object of type <class 'str'>**

**Comment by YingXue** [comment]
Unfortunately we not yet have a story around updating model typed properties. Update currently only support primitive types or if the property value is in the format of JSON for example device twin.
We would add routes and endpoints feature in the near future.
Sorry for the inconvenience.

**Comment by digimaun** [comment]
Like @YingXue said we don't yet have a primary story around updating hub routes and related assets, however there is somewhat of a workaround you can try until we do release the first class routing/endpoints functionality.
 
You can provide a python dictionary to --add, with the same attributes as the RouteProperties model which should be evaluated by AST to a dictionary, which then should be compatible with the model when making the request.
 
Here is an example:
 
az iot hub update -n YourHub --add properties.routing.routes "{'condition':'true', 'endpointNames':['events'], 'isEnabled':True, 'name':'defaulteventrount', 'source':'DeviceMessages'}"

**Comment by digimaun** [comment]
Closing as we have not heard back in some weeks. Please re-open to discuss more.
