### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by ropletal** [Azure/azure-iot-cli-extension#275]
## Describe the bug

**Command Name**
`az iot hub device-identity create
Extension Name: azure-iot. Version: 0.10.3.`

**Errors:**
```
Unable to find IoT Hub: ro-IoT-Hub in current subscription 88f19adf-5ffa-456e-80a2-7ed46ab55a47.
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az iot hub device-identity create --hub-name {} --device-id {}`

## Environment Summary
```
Linux-4.15.0-1098-azure-x86_64-with-debian-stretch-sid (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.14.0 *

Extensions:
azure-iot 0.10.3
ai-examples 0.2.4

```

**Comment by c-ryan-k** [comment]
@ropletal - could you run `az iot hub list -o table` and see if `ro-IoT-Hub` is listed in that subscription?

**Comment by c-ryan-k** [comment]
@ropletal if you run into this issue again please let us know - closing for now since it's been a couple weeks without a response.
