### ISSUE TITLE
[feature] Achieve etag consistency with other IoT Hub API

### ISSUE THREAD

**Issue by dapisani** [Azure/azure-iot-cli-extension#284]
**Describe**
When updating a module twin with the C# API, `RegistryManager.UpdateTwinAsync` has a parameter for etag to ensure consistency when updating a module twin.

The iot hub cli through `az iot hub module-twin update` does not seem to have this capability. As such it seems impossible to ensure module twin consistency when using the az cli.

**Environment**

- OS: Ubunu 18.04
- Shell: bash
- Az CLI version: 2.15.1
- IoT extension version:   "extensions": {"azure-cli-iot-ext": "0.8.9", "azure-iot": "0.10.7"}
- Python version (if pip installed): 3.6.9

**Comment by digimaun** [comment]
We'll support this in a near future release. But I also want to point if you have `azure-cli-iot-ext` installed, you should remove it. That was the legacy iot extension (which has been deprecated for some time)  prior to `azure-iot` - it will be deleted soon. There is no reason to have it installed anymore and it could cause more issues.

**Comment by dapisani** [comment]
I mainly use the azure-iot extension. This case I was using your container at mcr.microsoft.com/iotedge/iotedgedev.  Maybe that should be updated as well?

**Comment by digimaun** [comment]
We recently released [v0.10.8](https://github.com/Azure/azure-iot-cli-extension/releases/tag/v0.10.8) which should cover this ask. Please update, then let us know if you run into issues.
