### ISSUE TITLE
az monitor error

### ISSUE THREAD

**Issue by pandc** [Azure/azure-iot-cli-extension#300]
## Describe the bug

**Command Name**
`az iot hub monitor-events
Extension Name: azure-cli-iot-ext. Version: 0.8.5.`

**Errors:**
```
No module named 'azure.mgmt.iothub.iot_hub_client'
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 233, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 659, in execute
    raise ex
cli/core/commands/__init__.py, ln 722, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
...
cliextensions/azure-cli-iot-ext/azext_iot/_factory.py, ln 28, in iot_hub_service_factory
    from azure.mgmt.iothub.iot_hub_client import IotHubClient
ModuleNotFoundError: No module named 'azure.mgmt.iothub.iot_hub_client'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az iot hub monitor-events -n {}`

## Environment Summary
```
Linux-4.15.0-1103-azure-x86_64-with-debian-10.2 (Cloud Shell)
Python 3.6.10
Installer: DEB

azure-cli 2.18.0
azure-cli-iot-ext 0.8.5
azure-cli-ml 1.20.0

Extensions:
azure-cli-iot-ext 0.8.5
ai-examples 0.2.5
azure-cli-ml 1.20.0

```

**Comment by digimaun** [comment]
Hi @pandc, to resolve the issue please uninstall `azure-cli-iot-ext` and install `azure-iot`. See this issue for more info https://github.com/Azure/azure-iot-cli-extension/issues/165#issuecomment-614878544.

**Comment by digimaun** [comment]
If after applying the suggested fix you still have problems, feel free to comment here and we can re-open.

**Comment by pandc** [comment]
I solved the problem following your suggestions, thank you digimaun
