### ISSUE TITLE
[bug] Impossible to send a JSON null as method-payload

### ISSUE THREAD

**Issue by pboettch** [Azure/azure-iot-cli-extension#309]
It seems to be impossible to send a `null`-value (in JSON) as payload argument when invoking a device method.

- Not specifying `--mp` gives an empty object `{}`.
- `--mp ''` sends an empty string
- `--mp null` sends `None` and results in a None-payload (or null-pointer if iot-sdk-c) on the device-side

I'd like to receive the literal `null` on my device-side.

I tried to hack my local installation but I got stock in the mprest-serializer.

- OS: Debian
- Shell: bash
- Az CLI version: 2.18.0
- IoT extension version: 0.10.9
- Python version (if pip installed): 3.9.0

**Comment by digimaun** [comment]
Hi @pboettch -- If I understand what you are looking to do correctly, you want to pass the literal "null" string to your device. `--mp null`, which translates to a payload of null to the service (omission of this property is equivalent) which will call the device with a null message body, does not satisfy your use case.

If this is accurate, to support the literal null string, you can "double quote" the input. I see you are using a bash shell, so the following should work:

`--mp '"null"'`

**Comment by digimaun** [comment]
Investigated more and I've run into the issue you mentioned in the C device SDK. However it does not repro in the Node device SDK. Have to do a bit more testing to determine if its specifically a constraint for the C sdk. As you noted msrest serialization is removing optional properties with `None`/`null` values automatically.

If you are willing to hack your local installation, try this as a workaround:

- Edit the command handler [here](https://github.com/Azure/azure-iot-cli-extension/blob/dev/azext_iot/operations/hub.py#L1534) to look something like this:
![image](https://user-images.githubusercontent.com/28658112/106547110-6e7bb980-64c1-11eb-8914-5365f24ce7ff.png)

- One line edit [here](https://github.com/Azure/azure-iot-cli-extension/blob/dev/azext_iot/sdk/iothub/service/operations/devices_operations.py#L537)
![image](https://user-images.githubusercontent.com/28658112/106547302-d7fbc800-64c1-11eb-88ab-6271d26e1803.png)

Give that a shot, then we will do a bit more investigation and provide a general fix in an upcoming release.

**Comment by pboettch** [comment]
Thanks for your investigation.

> If this is accurate, to support the literal null string, you can "double quote" the input. I see you are using a bash shell, so the following should work:
> `--mp '"null"'`

You understood yourself in the meantime, but I'd like to emphasize: I'm not looking for the string-literal `"null"` but for `null` (both is JSON) and due to the conversion to Python (from JSON) `null` becomes `None` and never becomes `null` again on the device-(sdk)-side.

So, what I actually need, if JSON is not mandatory for an IoThub-device-method payload, is a `--raw-method-payload`-argument to `invoke-method`. Which could be either a file or a string and is _sent as such_, without trying to convert with `json.load()` but just as a byte-array?

Your workaround works for me. It does exactly what I'd describe as raw-payload.

**Comment by asergaz** [comment]
fyi same question asked in StackOverflow: https://stackoverflow.com/questions/65985330/how-to-invoke-a-device-method-with-no-method-payload-json-null-with-azure-cli

**Comment by asergaz** [comment]
@pboettch can you point us to places in Azure IoT Documentation where we mention this should be possible so we bring some more attention to this issue? Also add some detail on why you need "to send a null-value (in JSON) as payload argument when invoking a device method."

Thanks

**Comment by pboettch** [comment]
When I was using the iothub-explorer I could send "anything" as method-payload - so I using 'null' for `void`-like method-payloads. With this tool I can only send JSON and I _cannot_ send `null` (which is valid JSON). 

If you don't want to support it, please make it clear in the documentation and in the cli-help.

Where in the documentation is it written, that the method-payload can only be (a sub-selection) of JSON?

**Comment by asergaz** [comment]
fyi @rloutlaw as current author from docs side: https://docs.microsoft.com/en-us/cli/azure/iot?view=azure-cli-latest

Thank you for he details @pboettch . 

+ @digimaun fyi

**Comment by digimaun** [comment]
Here is a small update - we opened an issue https://github.com/Azure/azure-iot-sdk-c/issues/1924 on the C device SDK as the error that happens when the payload property is omitted should not be happening.

Then for the IoT CLI extension we'll introduce a fix that supports explicit null in the next release so you don't need to manually apply the workaround.

**Comment by digimaun** [comment]
`azure-iot v0.10.11` was recently released which should include the fix for this issue. Do you mind confirming before we close this issue?

**Comment by pboettch** [comment]
It looks good (including the test-case), but I'm not really able to test right now (and I changed my project to not use null-payloads anymore).

**Comment by pboettch** [comment]
I think this issue can be closed, I will re-open it if something comes up. Thanks.
