### ISSUE TITLE
Get connection  string fails

### ISSUE THREAD

**Issue by wertherc** [Azure/azure-iot-cli-extension#311]
## Describe the bug

**Command Name**
`az iot hub device-identity connection-string show
Extension Name: azure-iot. Version: 0.10.9.`

**Errors:**
```
Unable to deserialize to object: type, AttributeError: 'list' object has no attribute 'get'
Traceback (most recent call last):
python3.6/site-packages/msrest/serialization.py, ln 1416, in _deserialize
    found_value = key_extractor(attr, attr_desc, data)
python3.6/site-packages/msrest/serialization.py, ln 1160, in rest_key_extractor
    return working_data.get(key)
AttributeError: 'list' object has no attribute 'get'

...

python3.6/site-packages/msrest/serialization.py, ln 1160, in rest_key_extractor
    return working_data.get(key)
msrest.exceptions.DeserializationError: Unable to deserialize to object: type, AttributeError: 'list' object has no attribute 'get'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- after creatong an IotEdge device run this command to get connection string
- `az iot hub device-identity connection-string show --device-id={} --resource-group={} --hub-name={}`

## Expected Behavior
connection string returned

## Environment Summary
```
Linux-3.10.0-1160.11.1.el7.x86_64-x86_64-with-centos-7.9.2009-Core
Python 3.6.8
Installer: RPM

azure-cli 2.18.0

Extensions:
azure-iot 0.10.9

```

**Comment by digimaun** [comment]
Hey @wertherc , can you please run the command with `--debug` to ensure your inputs are valid? I was unable to repro unless in one case where I explicitly set  `--device-id=""`. Any details to help repro would be great.

**Comment by digimaun** [comment]
Closing this issue as we need more details to repro to identify the issue. Feel free to comment here and we can re-open.
