### ISSUE TITLE
Error when exporting iot hub devices

### ISSUE THREAD

**Issue by rmotyka** [Azure/azure-iot-cli-extension#313]
## Describe the bug

**Command Name**
`az iot hub device-identity export
Extension Name: azure-iot. Version: 0.9.1.`

**Errors:**
```
Unable to build a model: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get', DeserializationError: Unable to deserialize to object: type, AttributeError: 'str' object has no attribute 'get'
Traceback (most recent call last):
Temp\pip-unpacked-wheel-0bxt5m_r\msrest\serialization.py, ln 1416, in _deserialize
Temp\pip-unpacked-wheel-0bxt5m_r\msrest\serialization.py, ln 1181, in rest_key_case_insensitive_extractor
...
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az iot hub device-identity export -n {} --ik --bcu {}`

## Environment Summary
```
Windows-10-10.0.19041-SP0
Python 3.6.8
Installer: MSI

azure-cli 2.19.1

Extensions:
azure-iot 0.9.1

```

**Comment by digimaun** [comment]
This is not necessarily the root case. But just to rule it out, can you please try the command after updating the IoT extension i.e. `az extension update --name azure-iot`

**Comment by rmotyka** [comment]
I've updated the extension and tried to export from another Iot-hub another error has appeared: 

`An error occurred. If you contact a support representative please include this correlation identifier: 052fe7b5-691f-4d04-b10b-019f2ca6e04f, timestamp: 2021-02-18 07:42:50Z, errorcode: IH400007.`

When the --bcu arg was in file only message above. When I specified the uri in command line, additionally such messages has appeared:

`'sp' is not recognized as an internal or external command,
operable program or batch file.
'sv' is not recognized as an internal or external command,
operable program or batch file.
'sr' is not recognized as an internal or external command,
operable program or batch file.
'skoid' is not recognized as an internal or external command,
operable program or batch file.
'sktid' is not recognized as an internal or external command,
operable program or batch file.
'skt' is not recognized as an internal or external command,
operable program or batch file.
'ske' is not recognized as an internal or external command,
operable program or batch file.
'sks' is not recognized as an internal or external command,
operable program or batch file.
'skv' is not recognized as an internal or external command,
operable program or batch file.
'sig' is not recognized as an internal or external command,
operable program or batch file.`

**Comment by digimaun** [comment]
Thank you. The second error when specifying the uri inline is likely caused by [shell escape](https://docs.microsoft.com/en-us/cli/azure/use-cli-effectively#quoting-issues) issues. For example when using powershell you could try something as indicated [here](https://github.com/Azure/azure-iot-cli-extension/issues/79#issuecomment-509831651) for escaping. But it is easier to use the input from a file.

The first error is a service error. One thing to double check is your IoT Hub file upload configuration. Ensure the storage account and storage container configured for the hub match the SAS URI string you are using for input (assuming this is a key based export). Also ensure your container SAS URI has permissions for read, write and delete.

**Comment by digimaun** [comment]
Closing this issue for now as we haven't heard back from you. You can still comment on this issue and we can re-open and iterate if its still a problem after double checking your IoT Hub configuration as indicated in the [prior message](https://github.com/Azure/azure-iot-cli-extension/issues/313#issuecomment-781497621).
