### ISSUE TITLE
[bug] Add consistent experience across Azure Iot Central cli commands to use x-ms-request-id, x-ms-client-request-id headers 

### ISSUE THREAD

**Issue by gtrifonov** [Azure/azure-iot-cli-extension#314]
*In order to troubleshoot and diagnose issues while executing Iot Central cli  commands it will be helpful to utilize  following headers across all iot central extensions commands :
 
x-ms-request-id - https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-ncnbi/565d1b95-30cc-4782-aae5-ba636373f8b6
x-ms-client-request-id - https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-ncnbi/817da997-30d2-4cd3-972f-a0073e4e98f7
 
This will allow users to diagnose potential Iot Central  issues by providing these values in case of failures to customer support.

**Comment by digimaun** [comment]
@prbans  @valluriraj for CC

**Comment by prbans** [comment]
In favor of this change

**Comment by yang-hai-feng** [comment]
@valluriraj , do we already had this changes included?

**Comment by valluriraj** [comment]
@yang-hai-feng  - support is not included yet.

**Comment by lucadruda** [comment]
x-ms-client-request-id header has been added by #427
