### ISSUE TITLE
[bug] "az iot central device command history" does not produce command history (redux)

### ISSUE THREAD

**Issue by digimaun** [Azure/azure-iot-cli-extension#316]
To reproduce:

1. Execute the command `az iot central device command run`
   1. This works and a result object is returned.
1. Execute the command `az iot central device command history`
   1.  This command doesn't produce any entries in result collection returned. Waiting several minutes does not make a difference.

This same issue happened in the recent past, was fixed, and has manifested again.

**Comment by digimaun** [comment]
@prbans @valluriraj

**Comment by prbans** [comment]
@Jackbk

**Comment by digimaun** [comment]
Verified the issue stemming from the service has been fixed.
