### ISSUE TITLE
Monitor messages count for IoT central app

### ISSUE THREAD

**Issue by khalidw** [Azure/azure-iot-cli-extension#317]
Hi! Is there a way to monitor the consumption of my IoT central app? I want to check how much messages have been used so that I can keep an eye on my costing

**Comment by digimaun** [comment]
@prbans @valluriraj @Jackbk

**Comment by prbans** [comment]
You can check that information here - https://docs.microsoft.com/en-us/azure/iot-central/core/howto-monitor-application-health

I don't think this is currently available via CLI
