### ISSUE TITLE
[bug] send-d2c-message hangs after retrieving hub policy

### ISSUE THREAD

**Issue by stewartadam** [Azure/azure-iot-cli-extension#318]
**Describe the bug**
Attempting to run `az iot device send-d2c-message -n iot-name -g rg-name -d device-name --debug` hangs after retrieving the owner policy.

**To Reproduce**

1. Install Azure CLI for macOS via `brew`
2. Provision an IoT device
3. Run `az iot device send-d2c-message`

**Expected behavior**
`send-d2c-message` sends a message that appears via `az iot hub monitor-events`

**Environment (please complete the following information):**

- OS: MacOS 11.2.2
- Shell: bash
- Az CLI version:

```
azure-cli                         2.20.0

core                              2.20.0
telemetry                          1.0.6

Extensions:
front-door                        1.0.11
azure-iot                        0.10.10

Python location '/usr/local/Cellar/azure-cli/2.20.0/libexec/bin/python'
Extensions directory '/Users/stewartadam/.azure/cliextensions'

Python (Darwin) 3.8.8 (default, Feb 27 2021, 02:19:17) 
[Clang 12.0.0 (clang-1200.0.32.29)]
   ```
- IoT extension version: 0.10.10
- Python version (if pip installed): 3.8.8

**Additional context**
```
...
urllib3.connectionpool: https://management.azure.com:443 "POST /subscriptions/<redacted>/resourceGroups/<redacted>/providers/Microsoft.Devices/IotHubs/<redacted>/listkeys?api-version=2020-03-01 HTTP/1.1" 200 None
msrest.http_logger: Response status: 200
msrest.http_logger: Response headers:
msrest.http_logger:     'Cache-Control': 'no-cache'
msrest.http_logger:     'Pragma': 'no-cache'
msrest.http_logger:     'Transfer-Encoding': 'chunked'
msrest.http_logger:     'Content-Type': 'application/json; charset=utf-8'
msrest.http_logger:     'Content-Encoding': 'gzip'
msrest.http_logger:     'Expires': '-1'
msrest.http_logger:     'Vary': 'Accept-Encoding'
msrest.http_logger:     'Server': 'Microsoft-HTTPAPI/2.0'
msrest.http_logger:     'x-ms-ratelimit-remaining-subscription-writes': '1199'
msrest.http_logger:     'x-ms-request-id': '9a5209d5-5f35-47f0-8370-43efcda7fabf'
msrest.http_logger:     'x-ms-correlation-request-id': '9a5209d5-5f35-47f0-8370-43efcda7fabf'
msrest.http_logger:     'x-ms-routing-request-id': 'WESTUS2:20210309T024940Z:9a5209d5-5f35-47f0-8370-43efcda7fabf'
msrest.http_logger:     'Strict-Transport-Security': 'max-age=31536000; includeSubDomains'
msrest.http_logger:     'X-Content-Type-Options': 'nosniff'
msrest.http_logger:     'Date': 'Tue, 09 Mar 2021 02:49:40 GMT'
msrest.http_logger: Response content:
<redacted>
cli.azext_iot.iothub.providers.discovery: Using policy 'iothubowner' for IoT Hub interaction.

### <--- hangs here

^Ccli.knack.cli: Event: Cli.PostExecute [<function AzCliLogging.deinit_cmd_metadata_logging at 0x1085b2b80>]
cli.__main__: Command ran in 8.760 seconds (init: 0.108, invoke: 8.651)
telemetry.save: Save telemetry record of length 3104 in cache
telemetry.check: Negative: The /Users/stewartadam/.azure/telemetry.txt was modified at 2021-03-08 18:49:34.940962, which in less than 600.000000 s
```

Happy to provide privately full logs upon request, as they're littered with tokens and key values.

**Comment by digimaun** [comment]
Thanks for sending us this issue.

Does it manifest with a particular iot hub? Are you consistently getting the hanging behavior? Do other iot hub commands also hang?  I'd like to rule out transient service behavior.

**Comment by stewartadam** [comment]
`az iot hub event-monitor` didn't hang on the same IoT Hub. I tried `send-d2c-message` against a different IoT Hub and it doesn't appear to hang there. Any idea on what gives?

**Comment by digimaun** [comment]
To clarify does `send-d2c-message` still hang on the original hub having the issue?

**Comment by stewartadam** [comment]
Still hangs.

If it helps narrow, this IoT hub where it hangs is not in my home tenant; I'm added as an AAD B2B guest to a third party tenant and have been granted RBAC rights on some of their subs, and I've used `az account set` to set that subscription in the other tenant as the default (so I don't have to add `--subscription` to each az command).

The "other hub" I tested above that did not hang was in a subscription on my account's home tenant.

 Just to confirm my understanding, I can pick any device on the hub (it doesn't have to be online in that moment) to run `send-d2c-message`, correct?

**Comment by digimaun** [comment]
Thanks for the additional information.

For the question, you _should_ be able to use any device identity on the hub , but the device should not be online - you would likely run into issues with conflicting connections.

**Comment by stewartadam** [comment]
Gotcha - the device identity being used was offline, so that shouldn't be an issue here.

**Comment by digimaun** [comment]
@stewartadam - one important factor here, `az iot device send-d2c-message` currently works for symmetric key auth based devices. I am able to repro the issue you indicated by attempting to send-d2c-message against devices with auth type of x509 self-signed or x509 CA. Were the devices you were having issues with also non symmetric key auth?

**Comment by stewartadam** [comment]
That would be it, we're using X509 self-signed.

**Comment by digimaun** [comment]
In newer versions the IoT CLI should raise a client error stating only symmetric key device auth is supported for simulation.
