### ISSUE TITLE
[bug] Please bump the version of `jsonschema`

### ISSUE THREAD

**Issue by jiasli** [Azure/azure-iot-cli-extension#321]
**Describe the bug**

`azure-iot` relies on an old version `3.0.2` of [`jsonschema`](https://pypi.org/project/jsonschema/), causing conflict with `arcappliance`. Please bump it to the latest to avoid crushing Azure CLI's CI.

Detail: https://github.com/Azure/azure-cli/pull/17456

**Comment by digimaun** [comment]
`azure-iot`  `v0.10.11` was recently released that includes this change.
