### ISSUE TITLE
command az iot hub module-identity show with --module-id "$edgeAgent" fails

### ISSUE THREAD

**Issue by heikki0** [Azure/azure-iot-cli-extension#339]
## Describe the bug

**Command Name**
`az iot hub module-identity show
Extension Name: azure-iot. Version: 0.10.10.`

**Errors:**
```
Unable to deserialize to object: type, AttributeError: 'list' object has no attribute 'get'
Traceback (most recent call last):
python3.8/site-packages/msrest/serialization.py, ln 1428, in _deserialize
    found_value = key_extractor(attr, attr_desc, data)
python3.8/site-packages/msrest/serialization.py, ln 1172, in rest_key_extractor
    return working_data.get(key)
AttributeError: 'list' object has no attribute 'get'

...

python3.8/site-packages/msrest/serialization.py, ln 1172, in rest_key_extractor
    return working_data.get(key)
msrest.exceptions.DeserializationError: Unable to deserialize to object: type, AttributeError: 'list' object has no attribute 'get'
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `login az`
- tried and ran command: `az iot hub module-identity show --device-id {} --module-id "edgeAgent" --hub-name {}`, without `$` in module-id - and it did not work, but got an error: `{'Message': 'ErrorCode:ModuleNotFound;Device {} Module edgeAgent at IotHub {} not registered.', 'ExceptionMessage': 'Tracking ID:{}-G:8-TimeStamp:05/05/2021 07:04:54'}`, so I figured to ran command with `$` in the module-id name as it is represented in VScode, Azure IoT hub extension:
- `az iot hub module-identity show --device-id {} --module-id "$edgeAgent" --hub-name {}` [and written here](https://docs.microsoft.com/en-us/azure/iot-edge/troubleshoot?view=iotedge-2018-06) or to be precise there it is written without quotation marks "", but if you call `az iot hub module-identity show --device-id {} --module-id $edgeAgent --hub-name {}`, you get an error message: `argument --module-id/-m: expected one argument`

## Expected Behavior
get the state of the $edgeAgent module, and not break. If this is the wrong command then tell the user that this is the wrong way of calling the function, or if possible map "$edgeAgent" -> "edgeAgent" and just make it work?

## Environment Summary
```
macOS-11.2.3-x86_64-i386-64bit
Python 3.8.9
Installer: HOMEBREW

azure-cli 2.22.1

Extensions:
azure-iot 0.10.10

```

**Comment by digimaun** [comment]
@heikki0 thanks for submitting this issue. 

Try escaping the `$` symbol since it has special meaning in common shells. For example use '$edgeAgent' (wrapped in single quotes) `-m '$edgeAgent'`.

**Comment by heikki0** [comment]
`--module-id "\$edgeAgent"` worked. Thanks! Should have tried it by myself, but on the other hand, I don't think you want to use not-escaped `$` to break your cli though. Also, a note about this in the docs would not harm!

All the best
