### ISSUE TITLE
IoTEdge Deployment template returns a bad request when deploying with Azure CLI (azure-cli-iot-ext)

### ISSUE THREAD

**Issue by diirib** [Azure/azure-iot-cli-extension#35]
az : ERROR: ErrorCode:GenericBadRequest;BadRequest

I'm getting a BadRequest error when trying to run 'az iot edge deployment create'. The error is the same for templates that were valid with the preview version, and for templates valid for the new version (I'm copying the templates from a deployment created in the portal).
The code is part of deployment scripts that haven't changed and were working perfectly until today.

Templates attached for validation with sample data.

AzureCLI version: 2.0.39
azure-cli-iot-ext version: 0.4.3

UPDATE: deployment works correctly when using azure-cli-iot-ext version: 0.5.0

cc: @ralarcon
[DeploymentTemplates.zip](https://github.com/Azure/azure-iot-cli-extension/files/2158114/DeploymentTemplates.zip)

**Comment by digimaun** [comment]
Closing due to finding resolution - update to the latest iot extension version (currently 0.5.0).
