### ISSUE TITLE
az iot dps certificate verify (Operation returned an invalid status code 'Not Found')

### ISSUE THREAD

**Issue by mikermesh** [Azure/azure-iot-cli-extension#37]
Azure CLI: azure-cli (2.0.43)
IoT Extension: azure-cli-iot-ext (0.5.1)
Command: az iot dps certificate verify --dps-name "$dpsName" --resource-group "$resourceGroup"  --name VerifyCert --path ./Verification.cer --etag AAAAAAAAAAA=

I get the following error when trying to verify a certificate in DPS using a command similar to the one above. I am able to successfully run the 'az iot dps certificate create' and 'az iot dps certificate generate-verification-code' commands.

The error message is:

Operation returned an invalid status code 'Not Found'
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\knack\cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "C:\Users\trdai\AppData\Local\Temp\pip-install-8jgnm5o1\azure-cli-core\azure\cli\core\commands\__init__.py", line 369, in execute
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\Lib\site-packages\six.py", line 693, in reraise
    raise value
  File "C:\Users\trdai\AppData\Local\Temp\pip-install-8jgnm5o1\azure-cli-core\azure\cli\core\commands\__init__.py", line 343, in execute
  File "C:\Users\trdai\AppData\Local\Temp\pip-install-8jgnm5o1\azure-cli-core\azure\cli\core\commands\__init__.py", line 182, in __call__
  File "C:\Users\trdai\AppData\Local\Temp\pip-install-8jgnm5o1\azure-cli-core\azure\cli\core\__init__.py", line 436, in default_command_handler
  File "C:\Users\trdai\AppData\Local\Temp\pip-install-8jgnm5o1\azure-cli-iot\azure\cli\command_modules\iot\custom.py", line 277, in iot_dps_certificate_verify
  File "C:\Users\trdai\AppData\Local\Temp\pip-install-8jgnm5o1\azure-mgmt-iothubprovisioningservices\azure\mgmt\iothubprovisioningservices\operations\dps_certificate_operations.py", line 505, in verify_certificate
azure.mgmt.iothubprovisioningservices.models.error_details.ErrorDetailsException: Operation returned an invalid status code 'Not Found'

**Comment by YingXue** [comment]
This error looks like it is not able to find the verifiation certificate from the path provided. Can you try verify if the --path provided is valid maybe (.\ instead of ./ ) or try to provide a full path.
If you encountered futher errors, you can also try to verify the cert from the UI and see if works for comparison: [https://docs.microsoft.com/en-us/azure/iot-dps/how-to-verify-certificates ](url)

**Comment by mikermesh** [comment]
@YingXue 

Thanks for the reply. The verification via the Portal with the same certificate works successfully. However, I am trying to upload the verification cert programmatically using the azure cli.

If I enter an invalid path or filename, I get a different error "Errno 2] No such file or directory:".  I've found that the "Operation returned an invalid status code 'Not Found'" is usually associated with an invalid eTag.

One thing I've noticed is that the create and generate-verification-code commands result in different eTags. Here is the process below.

1. Issue az iot dps certificate create command and receive eTag.
2. Issue az iot dps certificate generate-verification-code command with eTag from Step #1.
3. This generates the Verification Code and an updated eTag.
4. Issue az iot dps certificate verify with a.) Verification Cert signed up uploaded cert and b.) updated etag from Step #3.

**Comment by YingXue** [comment]
Hi @mikermesh, the work flow that you've provided here is correct, though I also tried it myself, and find it working for me:
1. az iot dps certificate create --dps-name yingtest -g yingtest --name testcert -p ./testcert.cer
where i got etag AAAAAAAyIyo=
2. az iot dps certificate generate-verification-code --dps-name yingtest -g yingtest --name testcert --etag AAAAAAAyIyo=
where i got etag AAAAAAAyIzo=
3. az iot dps certificate verify --dps-name yingtest -g yingtest --name testcert -p ./verify.cer --etag AAAAAAAyIzo=
Not sure if you are doing anything different here?

For your reference, I have written some tests related to these command before, where you may find it helpful: [https://github.com/Azure/azure-cli/blob/dev/src/command_modules/azure-cli-iot/azure/cli/command_modules/iot/tests/latest/test_iot_dps_commands.py](url) (starting from line 87). There are several helper functions in the same folder, regarding to create testcert.cer and verify.cert

**Comment by YingXue** [comment]
I guss the problem might be **az iot dps certificate verify --dps-name "$dpsName" --resource-group "$resourceGroup" --name **VerifyCert** --path ./Verification.cer --etag AAAAAAAAAAA=** where --name should be the name of the same name in the first step. I could be wrong, as I am purely guessing judging the name of the cert you provided here :)

**Comment by mikermesh** [comment]
@YingXue You are 100% right...my command wasn't passing in the same cert name as step#1. I updated my script and it is working now. I'm closing the issue. Thanks for your help!
