### ISSUE TITLE
[bug] Cannot create enrollment group with allocation policy and linked IOT hubs

### ISSUE THREAD

**Issue by ramondeklein** [Azure/azure-iot-cli-extension#394]
I try to run the following command:
```
$  az iot dps enrollment-group create \
    --resource-group 'test-iot' \
    --dps-name 'my-iothub-dps' \
    --enrollment-id 'default' \
    --allocation-policy 'geolatency' \
    --iot-hub-host-name 'my-iothub-weu.azure-devices.net my-iothub-wus.azure-devices.net'
    ...
```
This results in the following error message: `'iot_hub_host_name' is not required when allocation-policy is defined.`

I checked the source-code and it seems there is a bug in the [_validate_allocation_policy_for_enrollment](https://github.com/Azure/azure-iot-cli-extension/blob/058648a794739d5f58c2574b3bc9081422d55f4e/azext_iot/operations/dps.py#L874) method. When an allocation policy is set, then it's forbidden to specify the IOT hub host names. It's currently only possible to create enrollment groups of type static (with a single IOT-hub) or without any linked IOT hubs.

The PowerShell version does allow to do this and has a [proper implementation](https://github.com/Azure/azure-powershell/blob/main/src/DeviceProvisioningServices/DeviceProvisioningServices/Cmdlet/IotDpsDataPlane/EnrollmentGroup/SetAzIotDeviceProvisioningServiceEnrollmentGroup.cs#L264). We have standardized our services to deploy using the AZ cli, but this prevents our system from being deployed automatically.

**Comment by digimaun** [comment]
@ramondeklein Please try using the parameter `--iot-hubs` instead of `--iot-hub-host-name` in your scenario i.e. `--iot-hubs 'my-iothub-weu.azure-devices.net my-iothub-wus.azure-devices.net'`

**Comment by ramondeklein** [comment]
@digimaun That works like expected. I wasn't aware of the different opties.
