### ISSUE TITLE
Unable to load extension 'azure-cli-iot-ext: unrecognized kwargs: ['min_profile']'. 'monitor-events' is misspelled or not recognized by the system.

### ISSUE THREAD

**Issue by bmoraa** [Azure/azure-iot-cli-extension#410]
Hi guys,
It seems this issue has been resolved but in my case is still going on. 
juan@Azure:~$ az --version
azure-cli                         2.27.0 *

core                              2.27.0 *
telemetry                          1.0.6

Extensions:
azure-cli-iot-ext                  0.7.0
azure-iot                        0.10.15
ai-examples                        0.2.5
ssh                                0.1.5

Python location '/opt/az/bin/python3'
Extensions directory '/home/juan/.azure/cliextensions'
Extensions system directory '/opt/az/lib/python3.6/site-packages/azure-cli-extensions'

Python (Linux) 3.6.10 (default, Jul 30 2021, 11:24:13)
[GCC 8.3.0]

juan@Azure:~$ az iot hub monitor-events --hub-name IOTSolHubRaspberry
Unable to load extension 'azure-cli-iot-ext: unrecognized kwargs: ['min_profile']'. Use --debug for more information.
Unable to load extension 'azure-iot: unrecognized kwargs: ['min_profile']'. Use --debug for more information.
'monitor-events' is misspelled or not recognized by the system.

What needs to be done? 
Thanks in advance !!

**Comment by digimaun** [comment]
Hey @bmoraa, `azure-cli-iot-ext` is deprecated and should be removed. Installing the legacy iot extension and `azure-iot`  at the same time will conflict. Try removing `azure-cli-iot-ext` with `az extension remove --name azure-cli-iot-ext` to see if it fixes the problem.

**Comment by bmoraa** [comment]
> Hey @bmoraa, `azure-cli-iot-ext` is deprecated and should be removed. Installing the legacy iot extension and `azure-iot` at the same time will conflict. Try removing `azure-cli-iot-ext` with `az extension remove --name azure-cli-iot-ext` to see if it fixes the problem.

Thank you digimaun, yes!! i just realize this.
Thank you any way, exactly what you say, is the way it was solved.
