### ISSUE TITLE
Tell user how to install extension in the deprecation notice

### ISSUE THREAD

**Issue by jongio** [Azure/azure-iot-cli-extension#45]
I ran an az iot command
```
jon@Azure:~$ az iot hub create --name jongiotfree --resource-group jongkeep --sku F1
```

And got this

```
Comprehensive IoT data-plane functionality is available
in the Azure IoT CLI Extension. For more info and install guide
go to https://github.com/Azure/azure-iot-cli-extension
```

Let's tell the user how to install in this message instead of making them go to github.

Add the following to the message:

`az extension add --name azure-cli-iot-ext`

**Comment by c-ryan-k** [comment]
This change has been merged into the Azure-CLI repo:
https://github.com/Azure/azure-cli/pull/7436#event-1877347512
