### ISSUE TITLE
[bug] monitor-events sys.excepthook issue when using keyboard interrupt (ctrl-c) on a Python 3.10 runtime

### ISSUE THREAD

**Issue by digimaun** [Azure/azure-iot-cli-extension#475]
**Describe the bug**
At least on a Python 3.10 runtime using `az iot hub monitor-events`, sys.excepthook errors are shown on keyboard interrupt. This was observed on a homebrew based install.

**To Reproduce**

- Install the azure-iot extension (`0.12.0`, `0.12.1`) on a Py 3.10.x based Azure CLI install. Run monitor-events and input keyboard interrupt. Observe errors.

**Expected behavior**
- Gracefully closing and deallocating resources. 

**Screenshots**

**Environment (please complete the following information):**

- OS: `MacOS`
- Shell: `bash`
- Az CLI version: `2.31.0`
- IoT extension version: `0.12.0`, `0.12.1`
- Python version (if pip installed):  `Python 3.10.x`

**Comment by lucadruda** [comment]
confirming for 3.9 as well on WSL2

**Comment by vilit1** [comment]
Closing since this was resolved.
