### ISSUE TITLE
Not clear which parameters are required

### ISSUE THREAD

**Issue by jongio** [Azure/azure-iot-cli-extension#48]
Entered
`az iot device send-d2c-message`

Got this
![image](https://user-images.githubusercontent.com/2163001/46561641-6c7f9c80-c8ad-11e8-9e24-7f32d1a207b1.png)

I would like some indication that tells me which parameters are required.

**Comment by digimaun** [comment]
I'm using azure cli 2.0.46

When entering `az iot device send-d2c-message` there is a notification before the usage info:

> az iot device send-d2c-message: error: the following arguments are required: --device-id/-d

To expand the parameters and see clear indicator for required, append `-h` or `--help` to the command i.e. `az iot device send-d2c-message -h`:

> Command
>     az iot device send-d2c-message : Send an mqtt device-to-cloud message.
>         Supports application and system properties to send with message.
> 
> Arguments
>     --device-id -d __[Required]__ : Target Device.
>     --da --data               : Message body.  Default: Ping from Az CLI IoT Extension.

Try testing the required notification with commands that have multiple required params

Input:
`az iot hub configuration create`

Output:
> az iot hub configuration create: error: the following arguments are required: --config-id/-c, --content/-k

**Comment by jongio** [comment]
If I provide -d, then it tells me I also need to provide a iot hub name or connection string.

![image](https://user-images.githubusercontent.com/2163001/46825979-b5ba6b00-cd49-11e8-9403-0f7174f5ca65.png)

Would be good for user to know that either one of those are required as well.

**Comment by jongio** [comment]
@digimaun can this be closed?

**Comment by digimaun** [comment]
Yea -- we have an upcoming release including change https://github.com/Azure/azure-iot-cli-extension/pull/389  which improves visibility + description of `--hub-name` and `--login`. Combined with improved Az CLI usage error output (which will output command examples) and an investigation activity for usage of argparse mutual exclusion https://github.com/Azure/azure-iot-cli-extension/issues/398.
