### ISSUE TITLE
Would be nice to tell user how to provide iot hub name

### ISSUE THREAD

**Issue by jongio** [Azure/azure-iot-cli-extension#49]
Entered this:

`az iot hub device-identity create -d d0`

Got this:
`Please provide an IoT Hub entity name or IoT Hub connection string via --login...`

It would be nice if it told me the name of the parameter for iothub...and entity name is confusing.  Shouldn't it just say provide iot hub name via the -n parameter?

**Comment by c-ryan-k** [comment]
Here's the PR for this: https://github.com/Azure/azure-iot-cli-extension/pull/50

Took a bit to get in due to some unit test issues with the new CI - but this should be good to go in our next release.
