### ISSUE TITLE
Unused import statements.

### ISSUE THREAD

**Issue by WilliamBerryiii** [Azure/azure-iot-cli-extension#5]
I believe the following imports can be removed:

https://github.com/Azure/azure-iot-cli-extension/blob/0284af28cbd11757e5d9449e47328a036e56a81f/azext_iot/commands.py#L7

https://github.com/Azure/azure-iot-cli-extension/blob/0284af28cbd11757e5d9449e47328a036e56a81f/setup.py#L8

**Comment by digimaun** [comment]
Leaving this open right now to validate CI style check.

**Comment by digimaun** [comment]
Fixed for next release. In dev to be merged to master.
