### ISSUE TITLE
Cannot Add Azure IoT Extension

### ISSUE THREAD

**Issue by ninghust** [Azure/azure-iot-cli-extension#576]
**Describe the bug**
Hi, I'm trying to add azure iot cli extension using command `az extension add --name azure-iot` but keep getting an error 

`Unable to get extension index.
Please ensure you have network connection. Error detail: HTTPSConnectionPool(host='aka.ms', port=443): Max retries exceeded with url: /azure-cli-extension-index-v1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f7f72893ac0>: Failed to establish a new connection: [Errno 111] Connection refused'))`
![image](https://user-images.githubusercontent.com/113426179/192241877-af55fbcd-89ba-4e37-a7ba-b58e4d6c134a.png)

Here is my azure version in WSL
![image](https://user-images.githubusercontent.com/113426179/192241791-f9eb14a3-edae-490d-a2c4-45fd7a2fb90e.png)

**Environment (please complete the following information):**

- OS: [ Ubuntu 22.04.1]
- Shell: [wsl bash]
- Az CLI version: [2.40.0]
- Python version (if pip installed): [3.10.5]

**Additional context**

**Comment by digimaun** [comment]
Hi @ninghust is this still an issue? When installing an extension by name, the CLI will first fetch the extension index and parse metadata of a target extension which includes compatible python runtimes, where an extension package is available, and its hash. The extension index fetch follows the redirect from the following url `https://aka.ms/azure-cli-extension-index-v1` to `https://azcliextensionsync.blob.core.windows.net/index1/index.json`. 

The error shows a network issue, can you please validate you are not under a network configuration that prevents access to the links I shared?

**Comment by ninghust** [comment]
> Hi @ninghust is this still an issue? When installing an extension by name, the CLI will first fetch the extension index and parse metadata of a target extension which includes compatible python runtimes, where an extension package is available, and its hash. The extension index fetch follows the redirect from the following url `https://aka.ms/azure-cli-extension-index-v1` to `https://azcliextensionsync.blob.core.windows.net/index1/index.json`.
> 
> The error shows a network issue, can you please validate you are not under a network configuration that prevents access to the links I shared?

Hi @digimaun, yes, it's still an issue...I can access `https://azcliextensionsync.blob.core.windows.net/index1/index.json` via web but from WSL ping it, cannot receive data.  Finally, I downloaded .whl extension file to my local and I installed iot extension.

**Comment by digimaun** [comment]
Understood. Have you looked into possible nameserver issues in `/etc/resolv.conf` ? This [stackoverflow thread](https://stackoverflow.com/questions/62314789/no-internet-connection-on-wsl-ubuntu-windows-subsystem-for-linux/63578387#63578387) has some other ideas to try as well.

Because the problems you are dealing with are with WSL configuration, and not az cli or the azure-iot extension, I'd like to close this issue as off-topic.

**Comment by digimaun** [comment]
Closing due to reasons explained [here](https://github.com/Azure/azure-iot-cli-extension/issues/576#issuecomment-1260121634).
