### ISSUE TITLE
[bug] IotCentral integration test failing trying execute app show -n {} command when test configuration has app id 

### ISSUE THREAD

**Issue by gtrifonov** [Azure/azure-iot-cli-extension#603]
**Describe the bug**
azext_iot/tests/central/__init__.py line 200:

```
else:
            self.app_rg = self.cmd(
                "iot central app show -n {}".format(
                    self.app_id,
                )
            ).get_output_in_json()["resourceGroup"]
```
iot central app show command expect application name to be passed. Currently according to documents settings.env.azext_iot_central_app_id can be  populated by user either with application id or application name. Error happens when pytest.ini has azext_iot_central_app_id populated with application id value and doesn't have  value in azext_iot_testrg and in azext_iot_central_token

**To Reproduce**

1. Go to pytest.ini
2. Paste value of application id into azext_iot_central_app_id 
3. Make sure that settings azext_iot_testrg and azext_iot_central_token are empty
4. Run pytest azext_iot/tests/central/test_iot_central_int.py
5. Tests are failing with message 
```
 No IoT Central application found with name {{application id from config}} in current subscription
```
**Expected behavior**
User should be able to use app id in test configuration otherwise setting need to be renamed to application name if going forward only name is acceptable

**Environment (please complete the following information):**

- OS: ANY
- Shell: Any
- Az CLI version: 2.43.0
- IoT extension version: 0.18.1
- Python version (if pip installed): 3.8.10

**Additional context**

**Comment by digimaun** [comment]
@HangyiWang , do you have cycles to take a look at this?

**Comment by HangyiWang** [comment]
> @HangyiWang , do you have cycles to take a look at this?

Sure

**Comment by digimaun** [comment]
Excellent, thank you.

**Comment by HangyiWang** [comment]
https://github.com/Azure/azure-iot-cli-extension/pull/621
