### ISSUE TITLE
[bug] az iot central diagnostics stops tracking events after a while

### ISSUE THREAD

**Issue by mmacagno** [Azure/azure-iot-cli-extension#635]
**Describe the bug**
The "az iot central diagnostics" will stop tracking events after 30 or so minutes.

**To Reproduce**

1. launch az iot central filtering on a specific device.
 
`iot central diagnostics monitor-events --app-id {my-app-id}  --properties all --device-id {my-device-id}`

2. observe the flow of events

**Expected behavior**
As the device keeps sending messages, the corresponding json events should flow on the console

***Actual***
The events stop flowing. No errors are displayed.
If I stop and restart the monitor, the events will start flowing again.

I confirmed that the device is sending events, receiving OK_EMPTY responses, and the IOT Central app is showing the device connected and events being received.

![image](https://user-images.githubusercontent.com/2315384/220815129-d0a3a40b-e81d-4c01-9341-bfd69f1be4b2.png)

**Environment:**

- OS: Windows 10
- Shell: CMD
- Az CLI version:

$ az version
{
  "azure-cli": "2.34.1",
  "azure-cli-core": "2.34.1",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "azure-iot": "0.13.0",
    "interactive": "0.4.5"
  }
}
- Python version (if pip installed): 3.10.5

**Comment by HangyiWang** [comment]
check in

**Comment by HangyiWang** [comment]
Try to repro this. But I can receive continuous event even after 2 hrs. 

And I'm using newer version: 
{
  "azure-cli": "2.39.0",
  "azure-cli-core": "2.39.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "azure-iot": "0.18.2"
  }
}

Could you please try update the CLI? @mmacagno

**Comment by mmacagno** [comment]
ok testing now @HangyiWang

**Comment by mmacagno** [comment]
@HangyiWang the updated CLI no longer manifests the issue.
Closing.
thanks
