### ISSUE TITLE
[bug] CLI fails when trying to delete a message-endpoint

### ISSUE THREAD

**Issue by sebastian-mg1** [Azure/azure-iot-cli-extension#650]
**Describe the bug**
When trying to run the command to delete a message-endpoint, the CLI throws an error and fails. Then I go to the portal to very if the endpoint was deleted, and the endpoint is still visible in the corresponding part of the portal.

**To Reproduce**
1. Setup and iothub in azure. Name it whatever you want 
2. Setup a message-route in azure
3. Try to delete it by running the following command:

```bash
IOT_HUB_NAME ="<your iot hub name here>"
ENDPOINT_NAME ="<your endpoint name here>"
az iot hub message-endpoint delete --hub-name $IOT_HUB_NAME --endpoint-name $ENDPOINT_NAME -y
```

5. Watch the command fail

**Expected behavior**
The command should fail and the endpoint should be gone after running the command.

**Example**
```bash
IOT_HUB_NAME="omitted-because-irrelevant"
ENDPOINT_NAME="SasTokenRequestsEndpoint"
$ az iot hub message-endpoint delete --hub-name $IOT_HUB_NAME --endpoint-name $ENDPOINT_NAME -y
Command group 'iot hub message-endpoint' is in preview and under development. Reference and support levels: https://aka.ms/CLI_refstatus
(400131) Enrichment has an undefined endpoint, Enrichment Key:iothub-connection-iothub-id, EndpointName:SasTokenRequestsEndpoint. If you contact a support representative please include this correlation identifier: 798865e0-fcbf-42c4-a1e6-7eca7713cb5a, timestamp: 2023-03-30 18:17:40Z, errorcode: IH400131.
Code: 400131
Message: Enrichment has an undefined endpoint, Enrichment Key:iothub-connection-iothub-id, EndpointName:SasTokenRequestsEndpoint. If you contact a support representative please include this correlation identifier: 798865e0-fcbf-42c4-a1e6-7eca7713cb5a, timestamp: 2023-03-30 18:17:40Z, errorcode: IH400131.
```

**Comment by digimaun** [comment]
Hi @sebsmgzz , to delete a message endpoint first the routes and msg enrichments associated with the endpoint need to be deleted. You can use the `az iot hub message-enrichment delete` command to delete existing enrichments.

After ensuring the removal of these associations, please let us know if deleting the message endpoint works.

**Comment by sebastian-mg1** [comment]
Hi @digimaun, you are correct. The endpoint had both, a message route and enrichment associations, after deleting does, the command deletes the endpoint as expected. I am running an automated script which isn't taking that into consideration. Thanks for the help.

**Comment by digimaun** [comment]
Cool very glad you got things working. Will close this issue.
