### ISSUE TITLE
[bug] list device-twins error: 'list' is misspelled

### ISSUE THREAD

**Issue by RotateAt60MPH** [Azure/azure-iot-cli-extension#662]
**Describe the bug**

Error displayed when listing device twins via Azure CLI.

**To Reproduce**

1. Open DOS command prompt
2. az login
3. az iot hub device-twin list 
4. error displayed

```
c:\Users\corey>az iot hub device-twin list
'list' is misspelled or not recognized by the system.
```

**Expected behavior**

Expect the device twins to be listed

**Environment (please complete the following information):**

- OS: Windows 10
- Shell: bash, cmd
- az cli version

```
{
  "azure-cli": "2.30.0",
  "azure-cli-core": "2.30.0",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {
    "azure-devops": "0.25.0",
    "azure-iot": "0.17.3"
  }
}

**Comment by c-ryan-k** [comment]
Hey @RotateAt60MPH - it looks like you're using an older version of our CLI extension where that `list` command does not yet exist.

It looks like it was introduced in our [`0.18.0`](https://github.com/Azure/azure-iot-cli-extension/releases/tag/v0.18.0) release, so you'll need to update your `azure-iot` extension to at least that version.

You can install the latest version [`0.21.2`](https://github.com/Azure/azure-iot-cli-extension/releases/tag/v0.21.2) by running `az extension update --name azure-iot`

Please let me know if that doesn't solve your issue and I can reopen this.

**Comment by c-ryan-k** [comment]
One more note, I also noticed your Azure CLI version is `2.30.0` - and in order to use our extension version `0.18.0` you will need to update your CLI to at least `2.32.0`, which is our required minimum version. 

If you update your extension to our newest version `0.21.2`, there's a minimum Azure CLI requirement of `2.37.0`.
