### ISSUE TITLE
Getting errors writing messages between Cloud and Device and vice versa

### ISSUE THREAD

**Issue by avinnako** [Azure/azure-iot-cli-extension#69]
Below are the errors i am getting while writing messages between Cloud and Device and vice versa:

1) AMQP Transport: Could not connect
2) NotConnectedError: connect ECONNREFUSED xxx.xxx.xx.xx:8883
3) [WinError 10061] No connection could be made because the target machine actively refused it

Please advise.

**Comment by digimaun** [comment]
Hi @avinnako.

Can you please describe your workflow and what command is not working?

Simple c2d scenario:

# Send c2d message to device
az iot device c2d-message send -d mydevice -n myhub --data "hello world!"

# Receive c2d message
az iot device c2d-message receive -d mydevice -n myhub

Simple d2c scenario:

# Run event monitor in a dedicated shell  (assumes default msg endpoint)
az iot hub monitor-events -n myhub

# Send d2c messages, and see event in monitor
az iot device send-d2c-message -n myhub-d mydevice


The more detail you provide the better for troubleshooting.

**Comment by avinnako** [comment]
I am no longer having communication issues from cloud to device. But I am still getting "[WinError 10061] No connection could be made because the target machine actively refused it" when i try to send message from device to cloud.

**Comment by avinnako** [comment]
I ran this command "az iot device send-d2c-message -n AVIoTHubTest -d Test-device-02" and "az iot device send-d2c-message -n AVIoTHubTest -d Test-device-02 --data "Hello World!"" and i got the same error: "[WinError 10061] No connection could be made because the target machine actively refused it" while trying from powershell.

**Comment by avinnako** [comment]
I am getting "NotConnectedError: connect ECONNREFUSED XXX.XXX.XXX.XXX:8883" while trying from VS Code, when trying to send message from device to cloud.

**Comment by digimaun** [comment]
Sorry for the delayed response. Assuming you resolved the issue. You can comment here if its still a problem and we can re-open the issue. If its still a problem my first inclination is a port issue, both vscode and the CLI using port 8883 for mqtt connection.
