### ISSUE TITLE
"az iot edge deployment create" should fail when IoT Hub exceeds quota limit

### ISSUE THREAD

**Issue by blackchoey** [Azure/azure-iot-cli-extension#72]
Expected behavior: When IoT Hub exceeds the quota limit (reaches max message count), create Edge deployment should fail.
Current behavior: `az iot edge deployment create ...` command will success with exit code 0

**Comment by blackchoey** [comment]
Hello, is there any update on this issue? Is this by design or it needs to be fixed?

**Comment by digimaun** [comment]
IoT Edge deployments do not count against your IoT Hub's message quota. This is by design.
