### ISSUE TITLE
ModuleNotFoundError: No module named 'wheel.wheelfile' when trying to follow contribution guidelines to install dev extension

### ISSUE THREAD

**Issue by scout208** [Azure/azure-iot-cli-extension#720]
Following along with the [Contribution guidelines ](https://github.com/Azure/azure-iot-cli-extension/blob/dev/CONTRIBUTING.md) to setup the Dev environment on my computer, I'm getting an error when running the command `pip install -U --target path/to/source/extensions/azure-iot .` in the "Install dev extension" section of the instructions. The error message is the following:

![Image](https://github.com/user-attachments/assets/a4092086-51ec-4d47-93e8-3ead60e98cb2)
![Image](https://github.com/user-attachments/assets/28b5b3b8-5302-401e-827c-b171e9a46871)

I'm using python version 3.12.

**Comment by vilit1** [comment]
There is an issue with the specific wheel files vs what the azure cli supports. We have pinned the version down in the dev_requirements:
https://github.com/Azure/azure-iot-cli-extension/blob/dev/dev_requirements#L9

Try running `pip install -r dev_requirements` and then rerunning the regular azure-iot install command.

**Comment by scout208** [comment]
That solved it. Thanks!
