### ISSUE TITLE
Do not print content of deployment manifest when creating Edge deployment

### ISSUE THREAD

**Issue by blackchoey** [Azure/azure-iot-cli-extension#73]
I'm using Azure CLI in Azure Pipelines to do Edge deployment. When I invoked the `az iot edge deployment create` command to create an Edge deployment, the output message contains the content of deployment manifest and will be persisted in Azure Pipelines task logs.
Since the deployment manifest may contain credentials, the credentials might be leaked in such situation. So please do not print the content of deployment manifest when creating Edge deployment.

**Comment by aaronpowell** [comment]
One option to work around this at the present time is to redirect the `stdout` to a variable, a file or a device (eg `/dev/null`), depending on whether you need anything from the response of the command.

**Comment by digimaun** [comment]
On top of what @aaronpowell said, the command is actually returning (not printing) the API response to the CLI output pipeline so you can choose the output 'none' option for a built in way for the CLI to suppress output i.e. `--output none`.

**Comment by digimaun** [comment]
Closing this for now since the command is returning the API response and there are methods, including first class supported (`--output none`) that suppress output.

Please re-open to discuss more.
