### ISSUE TITLE
"no matching extensions for azure-cli-iot-ext"

### ISSUE THREAD

**Issue by stevebus** [Azure/azure-iot-cli-extension#74]
when I try to install the azure-cli-iot-ext on an Ubuntu 16.04 linux, box, I get an error claiming no matching extension exists...

environment - Linux azureEdgeUbuntu1 4.15.0-1031-azure #32~16.04.1-Ubuntu SMP Wed Oct 31 19:20:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

azure cli version - azure-cli                         2.0.66

when I try to run 

az extension add --name azure-cli-iot-ext

I get this error...  
No matching extensions for 'azure-cli-iot-ext'. Use --debug for more information.

if I run it with --debug, I get..

Command arguments: ['extension', 'add', '--name', 'azure-cli-iot-ext', '--debug']
Event: Cli.PreExecute []
Event: CommandParser.OnGlobalArgumentsCreate [<function CLILogging.on_global_arguments at 0x7fbbe05ace18>, <function OutputProducer.on_global_arguments at 0x7fbbe00e4bf8>, <function CLIQuery.on_global_arguments at 0x7fbbdfe86c80>]
Event: CommandInvoker.OnPreCommandTableCreate []
Installed command modules ['acr', 'acs', 'advisor', 'ams', 'appservice', 'backup', 'batch', 'batchai', 'billing', 'botservice', 'cdn', 'cloud', 'cognitiveservices', 'configure', 'consumption', 'container', 'cosmosdb', 'deploymentmanager', 'dla', 'dls', 'dms', 'eventgrid', 'eventhubs', 'extension', 'feedback', 'find', 'hdinsight', 'interactive', 'iot', 'iotcentral', 'keyvault', 'kusto', 'lab', 'maps', 'monitor', 'natgateway', 'network', 'policyinsights', 'privatedns', 'profile', 'rdbms', 'redis', 'relay', 'reservations', 'resource', 'role', 'search', 'security', 'servicebus', 'servicefabric', 'signalr', 'sql', 'sqlvm', 'storage', 'vm']
Loaded module 'acr' in 0.005 seconds.
Loaded module 'acs' in 0.013 seconds.
Loaded module 'advisor' in 0.001 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'ams' in 0.006 seconds.
Loaded module 'appservice' in 0.007 seconds.
Loaded module 'backup' in 0.003 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'batch' in 0.009 seconds.
Loaded module 'batchai' in 0.003 seconds.
Loaded module 'billing' in 0.001 seconds.
Loaded module 'botservice' in 0.003 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'cdn' in 0.002 seconds.
Loaded module 'cloud' in 0.001 seconds.
Loaded module 'cognitiveservices' in 0.001 seconds.
Loaded module 'configure' in 0.001 seconds.
Loaded module 'consumption' in 0.002 seconds.
Loaded module 'container' in 0.002 seconds.
Loaded module 'cosmosdb' in 0.004 seconds.
Loaded module 'deploymentmanager' in 0.002 seconds.
Loaded module 'dla' in 0.004 seconds.
Loaded module 'dls' in 0.004 seconds.
Loaded module 'dms' in 0.002 seconds.
Loaded module 'eventgrid' in 0.002 seconds.
Loaded module 'eventhubs' in 0.003 seconds.
Loaded module 'extension' in 0.001 seconds.
Loaded module 'feedback' in 0.001 seconds.
Loaded module 'find' in 0.001 seconds.
Loaded module 'hdinsight' in 0.002 seconds.
Loaded module 'interactive' in 0.000 seconds.
Loaded module 'iot' in 0.004 seconds.
Loaded module 'iotcentral' in 0.001 seconds.
Loaded module 'keyvault' in 0.006 seconds.
Loaded module 'kusto' in 0.002 seconds.
Loaded module 'lab' in 0.004 seconds.
Loaded module 'maps' in 0.001 seconds.
Loaded module 'monitor' in 0.005 seconds.
Loaded module 'natgateway' in 0.001 seconds.
Loaded module 'network' in 0.033 seconds.
Loaded module 'policyinsights' in 0.002 seconds.
Loaded module 'privatedns' in 0.004 seconds.
Loaded module 'profile' in 0.002 seconds.
Loaded module 'rdbms' in 0.007 seconds.
Loaded module 'redis' in 0.002 seconds.
Loaded module 'relay' in 0.003 seconds.
Loaded module 'reservations' in 0.002 seconds.
Loaded module 'resource' in 0.007 seconds.
Loaded module 'role' in 0.004 seconds.
Loaded module 'search' in 0.002 seconds.
Loaded module 'security' in 0.003 seconds.
Loaded module 'servicebus' in 0.005 seconds.
Loaded module 'servicefabric' in 0.002 seconds.
Loaded module 'signalr' in 0.001 seconds.
Loaded module 'sql' in 0.007 seconds.
Loaded module 'sqlvm' in 0.002 seconds.
Event: CommandLoader.OnLoadCommandTable []
Loaded module 'storage' in 0.032 seconds.
Loaded module 'vm' in 0.014 seconds.
Loaded all modules in 0.242 seconds. (note: there's always an overhead with the first module loaded)
Extensions directory: '/home/stevebus/.azure/cliextensions'
Event: CommandInvoker.OnPreCommandTableTruncate [<function AzCliLogging.init_command_file_logging at 0x7fbbdfe08c80>]
az_command_data_logger : command args: extension add --name {} --debug
metadata file logging enabled - writing logs to '/home/stevebus/.azure/commands'.
Event: CommandInvoker.OnPostCommandTableCreate [<function register_global_subscription_argument.<locals>.add_subscription_parameter at 0x7fbbdfe26c80>, <function register_ids_argument.<locals>.add_ids_arguments at 0x7fbbdfddc7b8>, <function register_cache_arguments.<locals>.add_cache_arguments at 0x7fbbdfddc950>]
Event: CommandInvoker.OnCommandTableLoaded []
Event: CommandInvoker.OnPreParseArgs [<function _documentdb_deprecate at 0x7fbbdda64378>]
Event: CommandInvoker.OnPostParseArgs [<function OutputProducer.handle_output_argument at 0x7fbbe00e4c80>, <function CLIQuery.handle_query_parameter at 0x7fbbdfe86d08>, <function register_ids_argument.<locals>.parse_ids_arguments at 0x7fbbdfddc840>, <function handler at 0x7fbbdd96b378>]
Extensions directory: '/home/stevebus/.azure/cliextensions'
urllib3.connectionpool : Starting new HTTPS connection (1): aka.ms:443
urllib3.connectionpool : https://aka.ms:443 "GET /azure-cli-extension-index-v1 HTTP/1.1" 301 0
urllib3.connectionpool : Starting new HTTPS connection (1): azurecliextensionsync.blob.core.windows.net:443
urllib3.connectionpool : https://azurecliextensionsync.blob.core.windows.net:443 "GET /index1/index.json HTTP/1.1" 200 87461
No extension found with name 'azure-cli-iot-ext'
cli.azure.cli.core.util : No matching extensions for 'azure-cli-iot-ext'. Use --debug for more information.
No matching extensions for 'azure-cli-iot-ext'. Use --debug for more information.
az_command_data_logger : exit code: 1
telemetry.save : Save telemetry record of length 2488 in cache
telemetry.check : Negative: The /home/stevebus/.azure/telemetry.txt was modified at 2019-06-12 20:12:20.801253, which in less than 600.000000 s
command ran in 1.059 seconds.

**Comment by ScoGroMSFT** [comment]
Same behavior here - it was also reported by a customer that this was working yesterday but is broken today.

**Comment by underguiz** [comment]
Same issue here.

**Comment by iluican** [comment]
Thank you for reporting this. We're working to release a fix ASAP.

**Comment by c-ryan-k** [comment]
While we work through this issue - you can still install the extension from a url by using our previously released version:

`az extension add --source https://github.com/Azure/azure-iot-cli-extension/releases/download/v0.7.0/azure_cli_iot_ext-0.7.0-py2.py3-none-any.whl`

**Comment by c-ryan-k** [comment]
This should now be fixed, please let us know if this resurfaces.

**Comment by chegewara** [comment]
I have the same issue on Ubuntu 20.04 now

**Comment by c-ryan-k** [comment]
@chegewara  - are you still trying to install the `azure-cli-iot-ext` extension?

We've renamed the extension to `azure-iot` a bit ago, and have removed references to the old version.

Can you try adding the extension by  `--name azure-iot` and let me know if you run into issues?

**Comment by chegewara** [comment]
I am following this instructions:
https://github.com/espressif/esp-azure#setting-up-azure-cli

But i was able to install it with that command

> az extension add --source https://github.com/Azure/azure-iot-cli-extension/releases/download/v0.7.0/azure_cli_iot_ext-0.7.0-py2.py3-none-any.whl

Thanks for update anyway
