### ISSUE TITLE
Define timeouts in const at top of file

### ISSUE THREAD

**Issue by WilliamBerryiii** [Azure/azure-iot-cli-extension#8]
Can the various timeouts nested in this file be moved to the top of the file as consts for clarity?
E.G.
https://github.com/Azure/azure-iot-cli-extension/blob/0284af28cbd11757e5d9449e47328a036e56a81f/azext_iot/custom.py#L535

https://github.com/Azure/azure-iot-cli-extension/blob/0284af28cbd11757e5d9449e47328a036e56a81f/azext_iot/custom.py#L537

**Comment by digimaun** [comment]
I think it makes sense to have a _constants.py (or similar) file to house the various min/max thresholds and related items.

**Comment by digimaun** [comment]
Fixed for next release. In dev to be merged to master.
