### ISSUE TITLE
validate deployment.json when creating IoT Edge deployment

### ISSUE THREAD

**Issue by shizn** [Azure/azure-iot-cli-extension#84]
Developers wants to validate the json schema before doing the actual deployment.
The IoT Edge deployment schema file is here - http://json.schemastore.org/azure-iot-edge-deployment-2.0. and we can use this lib to do validation https://json-schema.org/implementations.html#validator-python

**Comment by digimaun** [comment]
This issue will be resolved in the next release.

**Comment by digimaun** [comment]
v0.8.2+ supports json schema validation for set-modules and deployment create commands.
