### ISSUE TITLE
az iot extension failing to deploy to a single device

### ISSUE THREAD

**Issue by fegonfe** [Azure/azure-iot-cli-extension#88]
## Describe the bug

**Command Name**
`az iot edge deployment create
Extension Name: azure-cli-iot-ext. Version: 0.8.0.`

**Errors:**
```
{'Message': "ErrorCode:InvalidConfigurationTargetCondition;Invalid targetCondition. It must be a filter condition based on 'deviceId', 'tags', or 'properties.reported'. It contains: edgeDeviceVM", 'ExceptionMessage': 'Tracking ID:6b8279e793d748528ba4b0a2fe486e21-G:3-TimeStamp:08/15/2019 21:59:21'}
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

I'm trying to create a deployment to a single device using the following syntax:
- `az iot edge deployment create --config-id {} --hub-name {} --content {} --target-condition deviceId='edgeDeviceVM' --priority {}`

## Expected Behavior
Deployment should work. It was working a few days ago.
Target condition is valid.
## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.70 *
azure-cli-iot-ext 0.8.0

Extensions:
azure-cli-iot-ext 0.8.0

```

**Comment by digimaun** [comment]
In your powershell environment for your use case you have to wrap the `--target-condition` argument in double quotes i.e. ` --tc "deviceId='edgeDeviceVM'"`.
