### ISSUE TITLE
Update .gitignore to exclude pytest default output directory

### ISSUE THREAD

**Issue by WilliamBerryiii** [Azure/azure-iot-cli-extension#9]
Currently the .gitignore for the extension includes the following section:

```
# Visual Studio cache files
# files ending in .cache can be ignored
*.[Cc]ache
# but keep track of directories ending in .cache
!*.[Cc]ache/
```

The draw back to having this in the .gitignore is that the default output directory for pytest is to put results in `.cache/v/cache/lastfailed`.  We could skirt this by defining the output directory for pytest in a script runner ... or loose the ability to track .cache directory for developers doing work in Visual Studio. Anyone have any thoughts on this?

**Comment by WilliamBerryiii** [comment]
Thinking about this more ... I think it's less likely that folks will be using Visual Studio to do python dev on this and as such, I think it's safe to downgrade the gitignore to a more python-centric exclusion list.  Thoughts?

**Comment by digimaun** [comment]
Fixed for next release. In dev to be merged to master.
