### ISSUE TITLE
Updating tags for (edge) device fails

### ISSUE THREAD

**Issue by hochas** [Azure/azure-iot-cli-extension#91]
## Describe the bug

**Command Name**
`az iot hub device-twin update
Extension Name: azure-cli-iot-ext. Version: 0.7.1.`

**Errors:**
```
pop from empty list
Traceback (most recent call last):
python3.6/site-packages/knack/cli.py, ln 206, in invoke
    cmd_result = self.invocation.execute(args)
cli/core/commands/__init__.py, ln 578, in execute
    raise ex
cli/core/commands/__init__.py, ln 636, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
cli/core/commands/__init__.py, ln 629, in _run_job
    six.reraise(*sys.exc_info())
...
cli/core/commands/arm.py, ln 806, in set_properties
    name, path = _get_name_path(key)
cli/core/commands/arm.py, ln 968, in _get_name_path
    return pathlist.pop(), pathlist
IndexError: pop from empty list
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- `az iot hub device-twin update --hub-name {} --device-id {} --set {} {} {}`

## Environment Summary
```
Linux-4.18.0-21-generic-x86_64-with-debian-buster-sid
Python 3.6.5
Shell: bash

azure-cli 2.0.69 *
azure-cli-iot-ext 0.7.1

Extensions:
azure-cli-iot-ext 0.7.1

```

**Comment by digimaun** [comment]
Take a look at [this wiki](https://github.com/Azure/azure-iot-cli-extension/wiki/Tips) for examples of using --set to update tags. The syntax depends on what shell you are using.

I just tried `az iot hub device-twin update -n myhub -d myedgedevice --set tags="{'location':{'region':'US'}}"` in powershell and it worked as expected.

**Comment by digimaun** [comment]
Please re-open to discuss further.

**Comment by hochas** [comment]
It was my error, I had a space in this location: `--set tags ="{}"`
