### ISSUE TITLE
0.8.2 is not installed when adding iot cli extension

### ISSUE THREAD

**Issue by blackchoey** [Azure/azure-iot-cli-extension#97]
When executing `az extension add --name azure-cli-iot-ext`, version 0.8.1 was installed instead of 0.8.2.
v0.8.1 currently prevents IoT Edge deployment on Azure Pipelines. I saw you have released v0.8.2 to fix the error. Please speed up the index refresh progress so users could get the fix as soon as possible.

**Comment by digimaun** [comment]
Just as an fyi, the PR for the index update is here https://github.com/Azure/azure-cli-extensions/pull/958.

**Comment by blackchoey** [comment]
Thank you very much. Just curious about the index update: Will the new version be available to all users once the PR is merged or it will take some additional time after the PR is merged?

**Comment by digimaun** [comment]
Yea, it may take up to an hour or so after merging. But we should now be good. Considering it resolved as of Sept 20th 2019, 5:36 PM EDT.

Please re-open the issue if still running into problems.
