### ISSUE TITLE
Misleading error when deployment manifest diesn't exist

### ISSUE THREAD

**Issue by barnstee** [Azure/azure-iot-cli-extension#99]
## Describe the bug

**Command Name**
`az iot edge set-modules
Extension Name: azure-cli-iot-ext. Version: 0.8.1.`

**Errors:**
```
improperly formatted json: Expecting value: line 1 column 1 (char 0)
```

## To Reproduce:
Steps to reproduce the behavior. Note that argument values have been redacted, as they may contain sensitive information.

- _Put any pre-requisite steps here..._
- `az iot edge set-modules --device-id {} --hub-name {} --content {}`

## Environment Summary
```
Windows-10-10.0.18362-SP0
Python 3.6.6
Shell: powershell.exe

azure-cli 2.0.70 *
azure-cli-iot-ext 0.8.1

Extensions:
azure-cli-iot-ext 0.8.1

```

**Comment by digimaun** [comment]
Resolved in v0.8.6 with resolution described in the release notes.
